#+title: 英语
* Word Power Made Easy
** How to use this book for maximum benefit
- [[file:2020111921-syllable.org][syllable]]
- [[file:2020111921-egomaniacal.org][egomaniacal]]
- [[file:2020111921-altercation.org][altercation]]
- [[file:2020111921-anthropological.org][anthropological]]
- [[file:2020111921-hissed.org][hissed]]
- [[file:2020112019-ambivalence.org][ambivalence]]
- [[file:2020112019-opulence.org][opulence]]
- [[file:2020112019-malign.org][malign]]
- [[file:2020112019-pagan.org][pagan]]
- [[file:2020112019-martinet.org][martinet]]
- [[file:2020112019-magnate.org][magnate]]
- [[file:2020112019-clandestinely.org][clandestinely]]
- [[file:2020112019-concerto.org][concerto]]
- [[file:2020112019-sorority.org][sorority]]
- [[file:2020112019-incorrigible.org][incorrigible]]
- [[file:2020112019-disparage.org][disparage]]
- [[file:2020112019-marry.org][marry]]
- [[file:2020112019-astronaut.org][astronaut]]
- [[file:2020112019-subtle.org][subtle]]
- [[file:2020112019-convention.org][convention]]
- [[file:2020112019-equivocate.org][equivocate]]
- [[file:2020112019-alternate.org][alternate]]
- [[file:2020112019-philander.org][philander]]
- [[file:2020112019-egoistic.org][egoistic]]
- [[file:2020112019-introverted.org][introverted]]
- [[file:2020112019-misogynous.org][misogynous]]
- [[file:2020112019-latent.org][latent]]
** How to test your present vocabulary
- [[file:2020112019-virtuoso.org][virtuoso]]
- [[file:2020112020-bumbling.org][bumbling]]
- [[file:2020112020-insulting.org][insulting]]
- [[file:2020112020-astonishing.org][astonishing]]
- [[file:2020110314-assess.org][assess]]
- [[file:2020112020-grasp.org][grasp]]
- [[file:2020112020-executives.org][executives]]
- [[file:2020112020-intimately.org][intimately]]
- [[file:2020112020-attaining.org][attaining]]
- [[file:2020112020-radical.org][radical]]
- [[file:2020112020-lull.org][lull]]
- [[file:2020112020-nuisance.org][nuisance]]
- [[file:2020112020-airy.org][airy]]
- [[file:2020112020-prodigious.org][prodigious]]
- [[file:2020112020-delusion.org][delusion]]
- [[file:2020112020-methuselah.org][methuselah]]
- [[file:2020112020-superstition.org][superstition]]
- [[file:2020112020-insatiable.org][insatiable]]
- [[file:2020112020-aspect.org][aspect]]
- [[file:2020112020-teaser.org][teaser]]
- [[file:2020112021-ramification.org][ramification]]
- [[file:2020112021-accustomed.org][accustomed]]
- [[file:2020112021-approximately.org][approximately]]
- [[file:2020112021-assimilate.org][assimilate]]
- [[file:2020112021-gobbing.org][gobbing]]

** How to talk about personality types
*** SESSION 1
**** IDEAS
***** [[file:2020112021-egoist.org][egoist]]
- [[file:2020112021-aboveboard.org][aboveboard]]
***** [[file:2020112109-egotist.org][egotist]]
- [[file:2020112021-conceit.org][conceit]]
- [[file:2020112021-amorous.org][amorous]]
- [[file:2020112021-boastful.org][boastful]]
- [[file:2020112021-obnoxious.org][obnoxious]]
- [[file:2020112021-interest.org][interest]]
***** [[file:2020112021-altruist.org][altruist]]
***** [[file:2020112021-introvert.org][introvert]]
- [[roam:probing]]
- [[file:2020112021-nagging.org][nagging]]
- [[file:2020112108-solitude.org][solitude]]
***** [[file:2020112108-extrovert.org][extrovert]]
- [[file:2020112108-dignity.org][dignity]]
- [[file:2020112108-propriety.org][propriety]]
***** [[file:2020112108-ambivert.org][ambivert]]
- [[file:2020112108-proportion.org][proportion]]
***** [[file:2020112108-misanthrope.org][misanthrope]]
- [[file:2020112108-embittered.org][embittered]]
- [[file:2020112108-crookedness.org][crookedness]]
***** [[file:2020112108-misogynist.org][misogynist]]
- [[file:2020112108-scorned.org][scorned]]
***** [[file:2020112108-misogamist.org][misogamist]]
***** [[file:2020112108-ascetic.org][ascetic]]
- [[file:2020112108-heir.org][heir]]
- [[file:2020112108-austerity.org][austerity]]
- [[file:2020112108-abstinence.org][abstinence]]
*** SESSION 2
**** Origin and relative words
- [[file:2020112109-excursions.org][excursions]]
***** the ego
- √ego meaning "I"
- [[file:2020112109-egomaniac.org][egomaniac]]
  - [[file:2020112109-morbid.org][morbid]]
  - [[file:2020112109-obsession.org][obsession]]
  - [[file:2020112109-mania.org][mania]]
***** others √alter
- [[file:2020112021-altruist.org][altruist]]
- [[file:2020112019-alternate.org][alternate]]
- [[file:2020112109-alternative.org][alternative]]
- [[file:2020111921-altercation.org][altercation]] is a verbal [[file:2020112109-dispute.org][dispute]]. is stronger than [[file:2020112109-quarrel.org][quarrel]] or [[file:2020112109-dispute.org][dispute]] the [[file:2020112109-sentiment.org][sentiment]], the disagreement is likely to be angry or even hot tem-tempered, there maybe [[file:2020112109-recourse.org][recourse]], if the [[file:2020112109-disputants.org][disputants]] are human, to [[file:2020112109-profanity.org][profanity]] or [[file:2020112109-obscenity.org][obscenity]], the word implies that you get quite excited.
- [[file:2020112109-alteration.org][alteration]] is of course a change, a making into something other.
- [[file:2020112109-alter_ego.org][alter ego]] 
**** Using the word
- [[file:2020112109-blow.org][blow]]
- [[file:2020112110-substitutes.org][substitutes]]
*** SESSION 3
**** Origin and relative words
***** depends how you turn
- √verto to turn
- the prefix ambi- also found in [[file:2020112110-ambidexterity.org][ambidexterity]]
  - [[file:2020112110-dexterous.org][dexterous]] means skillful, the noun [[file:2020112110-dexterity.org][dexterity]] is skill.
  - [[file:2020112110-dexter.org][dexter]] is a latin word for right hand, in the [[file:2020112110-ambidextrous.org][ambidextrous]] person both hands are right hands.
  - [[file:2020112110-left_handed.org][left-handed]] is still the synonym of awkward
  - the Latin word for the left hand is [[file:2020112110-sinister.org][sinister]]
  - The French word for the left hand is [[file:2020112110-gauche.org][gauche]]. A [[file:2020112110-gauche.org][gauche]] remark is [[file:2020112110-tactless.org][tactless]]. A [[file:2020112110-gauche.org][gauche]] offer of a sympathy is so [[file:2020112020-bumbling.org][bumbling]] to be embarassing. [[file:2020112110-gaucherie.org][gaucherie]] is an awkward, [[file:2020112110-clumsy.org][clumsy]], [[file:2020112110-tactless.org][tactless]], embarrassing way of saying things or of handling situation. The [[file:2020112110-gauche.org][gauche]] person is totally without [[file:2020112110-finesse.org][finesse]].
  - And the French word for the right hand is [[file:2020112110-droit.org][droit]], which we have used in building our English word adroit ( a-DROYT'). Needless to say, adroit, like dexterous, means skillful, but especially in the exercise of the mental [[file:2020112110-facilities.org][facilities]]. Like gauche, adroit, or its [[file:2020112110-nounadroitness.org][nounadroitness]], usually is used [[file:2020112110-figuratively.org][figuratively]]. The adroit person is quick-witted, can get out of difficult spots cleverly, can handle situations [[file:2020112110-ingeniously.org][ingeniously]]. Adroitness is, then, quite the opposite of gaucherie.
***** love,hate,and marriage
****** √misein to hate
Misanthrope, misogynist, and misogamist are built on the Greek root ~misein~, to hate. The misanthrope hates mankind (Greek ~anthropos~, mankind); the misogynist hates women (Greek ~gyne~, woman); the misogamist hates marriage (Greek ~gamos~, marriage). Anthropos, mankind, is also found in [[file:2020112110-anthropology.org][anthropology]] (an-thra-POL'-a-jee), the study of the development of the human race; and in [[file:2020112110-philanthropist.org][philanthropist]] (fa-LAN'-thra-pist), one who loves man-kind and shows such love by making [[file:2020112110-substantial.org][substantial]] financial contributions to charitable organizations or by donating time and energy to helping those in need. The root gyne, woman, is also found in [[file:2020112110-gynecologist.org][gynecologist]]  jin· -KOL'-a-jist, the medical specialis treats female disorders. And the root gamos, marriage, occurs also in [[file:2020112110-monogamy.org][monogamy]] (rna-NOG'-a-mee), [[file:2020112110-bigamy.org][bigamy]] (BIG'-a-rnee), and [[file:2020112110-polygamy.org][polygamy]] (pa-LIG'-a-mee). (As we will discover later, monos means one, bi- means two, polys means many.)
So monogamy is the custom of only one marriage (at a time).
Bigamy, by etymology, is two marriages-in actuality, the unlawful act of contracting another marriage without divorcing one's current legal spouse.
And polygamy, by derivation many marriages, and therefore etymologically [[file:2020112111-denoting.org][denoting]] [[file:2020112111-plural.org][plural]] marriage for either males or females, in current usage generally refers to the custom practiced in earlier times by the [[file:2020112111-mormons.org][Mormons]], and before them by King Solomon, in which the man has as many wives as he can afford financially and/or emotionally. The correct, but rarely used, term for this custom is polygyny (p;;i-LIJ'-a-nee)-polys, many, plus gyne,woman.
What if a woman has two or more husbands, a form of marriage practiced in the Himalaya Mountains of Tibet? That custom is called [[file:2020112111-polyandry.org][polyandry]] (pol-ee-AN'-dree), from polys plus Greek
~andros~, male.
***** making friends with suffixes
***** living alone and liking it √asketes
[[file:2020112111-ascetic.org][Ascetic]] is from the Greek word ~asketes~, monk or hermit.
A monk lives a lonely life-not for him the pleasures of the fleshpots, the [[file:2020112111-laughter.org][laughter]] and [[file:2020112111-merriment.org][merriment]] of [[file:2020112111-convivial.org][convivial]] gatherings, the [[file:2020112111-dissipation.org][dissipation]] of high living. Rather, days of contemplation, study, and rough [[file:2020112111-toil.org][toil]], nights on a hard bed in a simple cell, and the kind of self-denial that leads to a [[file:2020112111-purification.org][purification]] of the soul.
That person is an ascetic who leads an existence, voluntarily of course, that compares in [[file:2020112111-austerity.org][austerity]], simplicity, and [[file:2020112111-rigorous.org][rigorous]] hardship with the life of a monk.
The practice is [[file:2020112111-asceticism.org][asceticism]] (a-SET'-;l-siz-am), the adjective ascetic.
**** REVIEW OF [[file:2020112111-etymology.org][ETYMOLOGY]]
| ego       | self, I                  |
| alter     | other                    |
| intro-    | inside                   |
| extro-    | outside                  |
| verto     | turn                     |
| ambi-     | both                     |
| misein    | hate                     |
| anthropos | mankind                  |
| gyne      | woman                    |
| gamos     | marriage                 |
| asketes   | monk                     |
| centrum   | center                   |
| mania     | madness                  |
| dexter    | right hand               |
| sinister  | left hand                |
| gauche    | left hand                |
| droit     | right hand               |
| monos     | one                      |
| bi-       | two                      |
| polys     | many                     |
| andros    | male                     |
| -ist      | person who (noun suffix) |
| -y        | practive custiom ,etc.   |
| -ous      | adjective suffix         |
| -ity      | quality condition        |

**** Using the words
- [[file:2020112113-asset.org][asset]]
- [[file:2020112113-hatred.org][hatred]]

**** TEASER QUESTIONS FOR THE AMATEUR ETYMOLOGIST
- [[file:2020112113-anthropocentric.org][anthropocentric]]
- [[file:2020112113-andromania.org][andromania]]
- [[file:2020112113-gynandrous.org][gynandrous]]
- [[file:2020112113-monomania.org][monomania]]
- [[file:2020112113-misandrist.org][misandrist]]

**** STICK TO YOUR TIME SCHEDULE!
- [[file:2020112113-unduly.org][unduly]]
- [[file:2020112113-gratified.org][gratified]]
- [[file:2020112113-thrill.org][thrill]]
- [[file:2020112114-persevere.org][persevere]]

*** Brief [[file:2020112114-intermission.org][Intermission]] One
**** TEST YOUR GRAMMAR
***** TEST1
- [[file:2020112114-proper.org][proper]]
***** TEST2
- [[file:2020112114-cinch.org][cinch]]
***** TEST3
- [[file:2020112114-creditably.org][creditably]]
- [[file:2020112114-criteria.org][criteria]]
** HOW TO TALK ABOUT DOCTORS
- [[file:2020112115-ailments.org][ailments]]
*** IDEAS
**** what's wrong with you?
To find out what ails you and why, this specialist gives you a thorough physical examination, using an impressive array of tests: X ray,. blood chemistry, urinalysis, cardiogram, and so on.
An [[file:2020112209-internist.org][internist]]

**** female troubles?
This specialist treats the female reproductive and sexual organs.
A [[file:2020112110-gynecologist.org][gynecologist]]

**** having a baby?
This specialist delivers babies and takes care of the mother during and immediately.after the period of her pregnancy.
An [[file:2020112209-obstetrician.org][obstetrician]]

**** is your baby ill?
You know the common childhood maladies-mumps, whooping cough, chicken pox, [[file:2020112209-measles.org][measles]]. This specialist limits his practice to youngsters, taking care of babies directly after birth, [[file:2020112209-supervising.org][supervising]] their diet and watching over their growth and development, giving them the series of [[file:2020112209-inoculations.org][inoculations]] that has done so much to decrease infant [[file:2020112209-mortality.org][mortality]], and [[file:2020112209-soothing.org][soothing]] their anxious parents.
A [[file:2020112209-pediatrician.org][pediatrician]]

**** skin clear?
You have heard the classic [[file:2020112209-riddle.org][riddle]]: "What is the best use for pigskin?" Answer: "To keep the pig together." Human skin has a similar purpose: it is, if we get down to fundamentals, what keeps us all in one piece. And our outer covering, like so many of our internal organs, is subject to diseases and infections of various kinds, running the [[file:2020112209-gamut.org][gamut]] from simple [[file:2020112209-acne.org][acne]] and [[file:2020112209-eczemas.org][eczemas]] through [[file:2020112209-impetigo.org][impetigo]], [[file:2020112209-psoriasis.org][psoriasis]], and cancer. There is a specialist who treats all such skin diseases. 
A [[file:2020112209-dermatologist.org][dermatologist]]

**** eyes okay?
The physician whose specialty is disorders of vision ([[file:2020112209-myopia.org][myopia]], [[file:2020112209-astigmatism.org][astigmatism]], [[file:2020112209-cataracts.org][cataracts]], [[file:2020112209-glaucoma.org][glaucoma]], etc.) may [[file:2020112209-prescribe.org][prescribe]] glasses, administer drugs, or perform surgery.
An [[file:2020112209-ophthalmologist.org][ophthalmologist]]

**** how are your bones?
This specialist deals with the skeletal structure of the body, treating bone fractures, slipped discs, [[file:2020112209-clubfoot.org][clubfoot]], [[file:2020112209-curvature.org][curvature]] of the spine, dislocations of the hip, etc., and may correct a condition either by surgery or by the use of braces or other appliances.
An [[file:2020112209-orthopedist.org][orthopedist]]

**** does yaur heart go pitter-patter?
This specialist treats diseases of the heart and circulatory system.
A [[file:2020112209-cardiologist.org][cardiologist]]

**** 9. is your brain working?
This physician specializes in the treatment of disorders of the brain, spinal cord, and the rest of the nervous system.
A [[file:2020112209-neurologist.org][neurologist]]

**** are you neurotic?
This specialist attempts to [[file:2020112209-alleviate.org][alleviate]] mental and emotional disturbances by means of various techniques, occasionally drugs or electroshock, more often private or group psychotherapy.
A [[file:2020112209-psychiatrist.org][psychiatrist]]

*** ORIGINS AND RELATED WORDS
**** inside you
Internist and internal derive from the same Latin root, ~internus~, inside. The internist is a specialist in internal medicine, in the exploration of your insides. This physician determines the state of your internal organs in order to discover what's happening within your body to cause the troubles you're complaining of. Do not confuse the internist with the [[file:2020112210-intern.org][intern]] (also spelled interne), who is a medical graduate serving an [[file:2020112210-apprenticeship.org][apprenticeship]] inside a hospital

**** doctors for women
The word [[file:2020112110-gynecologist.org][gynecologist]] is built on Greek ~gyne~, woman, plus ~logos~, science; etymologically, gynecology is the science (in actual use, the medical science) of women. [[file:2020112210-adjective.org][Adjective]]: gynecological (gin [or jin or jinJ-a-kQ-LOJ'-a-kal). [[file:2020112210-obstetrician.org][Obstetrician]] derives from Latin ~obstetrix~, midwife, which in turn has its source in a Latin verb meaning to stand-midwives stand in front of the woman in labor to aid in the delivery of the infant. The suffix ~-ician~, as in obstetrician, physician, musician, magi- cian, electrician, etc., means expert. Obstetrics (ob-STET'-riks) has only within the last 150 years become a respectable specialty. No further back than 1834, Professor William P. Dewees [[file:2020112210-assumed.org][assumed]] the first chair of obstetrics at the University of Pennsylvania and had to brave considerable medical contempt and [[file:2020112210-ridicule.org][ridicule]] as a result-the delivery of children was then considered beneath the [[file:2020112108-dignity.org][dignity]] of the medical profession. Adjective: obstetric (ob-STET'-rik) or obstetrical (ob-STET'- ra-kal).

**** children
Pediatrician is a combination of Greek ~paidos~, child; ~iatreia~, medical healing; and -ician, expert. · Pediatrics (pee-dee-AT'-riks), then, is by etymology the medical healing of a child. Adjective: pediatric (pee-dee-AT'-rik). (The ped- you see in words like [[file:2020112210-pedestal.org][pedestal]], [[file:2020112210-pedal.org][pedal]], and [[file:2020112210-pedestrian.org][pedestrian]] is from the Latin ~pedis~, foot, and [[file:2020112210-despite.org][despite]] the identical spelling in English has no relationship to Greek ~paidos~.) [[file:2020112210-pedagogy.org][Pedagogy]] (PED-a-go'-jee), which combines ~paidos~ with ~agogos~, leading; is, etymologically, the leading of children. And to what do you lead them? To learning, to development, to growth, to maturity. From the moment of birth, infants are led by adults- they are taught, first by parents and then by teachers, to be self-sufficient, to *fit into* the culture in which they are born. Hence, pedagogy, which by derivation means the leading of a child, refers actually to the principles and methods of teaching. College students majoring in education take certain standard pedagogy courses-the history of education; educational psychology; the psychology of [[file:2020112210-adolescents.org][adolescents]]; principles of teaching; etc. Adjective: pedagogical (ped-a-GOJ'-a-kal). A pedagogue (PED'-:i-gog) is versed in pedagogy. But [[file:2020112210-pedagogue.org][pedagogue]] has an unhappy history. From its original, neutral meaning of teacher, it has deteriorated to the point where it refers, today, to *a* *narrow-minded*,[[file:2020112210-strait_laced.org][strait-laced]] ,old-fashioned, [[file:2020112210-dogmatic.org][dogmatic]] teacher. It is a word of contempt and should be used with caution. Like. pedagogue, [[file:2020112210-demagogue.org][demagogue]] (DEM'-a-gog) has also deteriorated in meaning. By derivation a leader (agogos) of the people (~demos~), a demagogue today is actually one who attempts, in [[file:2020112210-essence.org][essence]], to mislead the people, a politician who foments discontent among the masses, [[file:2020112210-rousing.org][rousing]] them to fever [[file:2020112210-pitch.org][pitch]] by wild [[file:2020112210-oratory.org][oratory]], in an attempt to be voted into office. Once elected, demagogues use political power to further their
own personal ambitions or fortunes. Many "leaders" of the past and present, in countries around the world, have been [[file:2020112210-accused.org][accused]] of demagoguery ( dem-a-(]OG' -a-ree) . Adjective: demagogic (dem-a-GOJ'-ik).
**** skin-deep
The [[file:2020112209-dermatologist.org][dermatologist]], whose specialty is dermatology ( dur-ma- TOL'-a-jee), is so named from Greek ~derma~, skin. Adjective: dermatological ( dur'-ma-ta-LOJ'-a-kal). See the syllables derma in any English word and you will know there is some reference to skin-for example, a [[file:2020112210-hypodermic.org][hypodermic]] . (hi~ pa-DUR'..,mik) needle [[file:2020112210-penetrates.org][penetrates]] under (Greek, ~hypos~) the skin,· the [[file:2020112210-epidermis.org][epidermis]] (ep-:i-DUR'-mis) ·is the outermost layer of skin; a [[file:2020112210-taxidermist.org][taxidermist]] (TAKS'-a-dur-mist), whose business is [[file:2020112210-taxidermy.org][taxidermy]] (TAKS'-a-dur-mee), prepares, stuffs, and mounts the skins of animals; a [[file:2020112210-pachyderm.org][pachyderm]] (PAK'-a-durm) is an animal with an unusually [[file:2020112210-thick.org][thick]] skin, like an elephant, [[file:2020112210-hippopotamus.org][hippopotamus]], or [[file:2020112210-rhinoceros.org][rhinoceros]]; and [[file:2020112210-dermatitis.org][dermatitis]] (dur-ma-Ti'-tis) is the general name for any skin inflammation, [[file:2020112210-irritation.org][irritation]], or infection.
**** the eyes have it
Ophthalmologist-note the ph preceding th-is from Greek ~ophthalmos~, eye, plus ~·logos~, science or study. The specialty is ophthalmology (off'-thal-MOU-a-jee), the adjective ophthal-mological ( off'-thal-ma-LOJ'-a-kal). An earlier title for this physician, still occasionally used, is ocu- list (OK'-ya-list), from Latin [[file:2020112210-oculus.org][oculus]], eye, a root on which the following English words are also built:
1. [[file:2020112210-ocular.org][ocular]] (OK'-ya-Iar)-an adjective that refers to the eye
2. [[file:2020112210-monocle.org][monocle]] (MON'-a-kal)-a lens for one (monos) eye, sported by characters in old movies as a symbol of the British so-called upper class
3. [[file:2020112210-binoculars.org][binoculars]] (ba-NOK'-ya-larz)-field glasses that increase the range of two (bi-) eyes
4. And, strangely enough, [[file:2020112210-inoculate.org][inoculate]] (in-OK'-ya-layt'), a word commonly [[file:2020112210-misspelled.org][misspelled]] with two n's. When you are inoculated against a disease, an "eye," [[file:2020112210-puncture.org][puncture]], or hole is made in your skin, through which [[file:2020112210-serum.org][serum]] is injected. Do not confuse the ophthalmologist or oculist, a medical specialist, with two other [[file:2020112210-practitioners.org][practitioners]] who deal with the eye-the [[file:2020112210-optometrist.org][optometrist]] (op-TOM'-a-trist) and [[file:2020112210-optician.org][optician]] (op-TISH'-an). Optometrists are not [[file:2020112210-physicians.org][physicians]], and do not perform surgery or administer drugs; they measure vision, test for [[file:2020112209-glaucoma.org][glaucoma]], and prescribe and fit glasses. Opticians fill an optometrist's or ophthalmologist's prescription, [[file:2020112211-grinding.org][grinding]] lenses according to specifications; they do not [[file:2020112211-examine.org][examine]] patients. Optometrist combines Greek ~opsis~, ~optikos~, sight or vision, with ~metron~, measurement .the optometrist, by etyi:pology, is one who measures vision. The specialty is [[file:2020112211-optometry.org][optometry]] (op-TOM'-a-tree).
Optician is built on opsis, optikos, plus -ician, expert. The specialty is optics (OP'-tiks). Adjectives: optometric ( op-ta-MET'-rik) or optometrical (op- ta-MET'-ra-kal), optical (OP'-ta-kal).
*** REVIEW OF ETYMOLOGY
| PREFIX, ROOT, SUFFIX | MEANING        |
|----------------------+----------------|
| internus             | inside         |
| gyne                 | woman          |
| obstetrix            | [[file:2020112211-midwife.org][midwife]]        |
| paidos               | child          |
| pedis                | foot           |
| agogos               | leader,leading |
| demos                | people         |
| derma                | skin           |
| hypos                | under          |
| ophthalmos           | eye            |
| oculus               | eye            |
| monos                | one            |
| bi-                  | two            |
| -ician               | expert         |
| opsis, optikos       | vision         |
| metron               | measurement    |
* 英语听力
** 19-8-interview(2)
- [[file:2020111910-disciplinary.org][disciplinary]]
- [[file:2020111910-literacy.org][literacy]]
sciplinary literacy (学科素养)
- [[file:2020110313-convince.org][convince]]
- [[file:2020111911-affiliation.org][affiliation]]
- [[file:2020111911-assessment.org][assessment]]
- [[file:2020111911-interpreting.org][interpreting]]
- [[file:2020111911-sophisticated.org][sophisticated]]
- [[file:2020111911-weigh.org][weigh]]
- [[file:2020111911-engage.org][engage]]
** 19-8-interview(1)
- hey cathy did you read this article in this magazine?I cant believe how much man is changing the planet.
- yeah I had a look at it, quite intresting I suppose if you believe that sort of thing
- what? what do you mean if you believe that sort of thing
- are you saying you dont believe that we are damaging the planet?
- to be honest mark, not really
- what do you saying, are you saying global warming isn't a fact, deforestation isn't a fact, the greenhouse effect isn't actually happening?
- hey calmdown mark, I just think too many people take these things as been(❎) being(✔) definitely true without knowking all the facts
- you really dont think global warming is happening
- you know they have said sea levels are going to rise by quite a few meters over the next fifty to a hundread years
- wheather conditons are getting worse all over the world
- can you remember how many big hurricanes there have been in the country over the last few years
- I think evidence is around us
- I dont think we have enough infomation to be honest, we have only being measuring these things for around two or three hundread years
- we have no idea what was happening fifty thousands years ago.
- for all we know this is just a natural [[file:2020111916-blip.org][blip]], a kind of sudden but temperary change, in the whole climate cycle
- I dont think we should change how we living just because of twenty years of abnormal measurements.
- and dont you think all the other effcets we are having on the planets are destructive?
- and what do you mean?
- I mean like deforestation,overpopulation,threatening the existence of extincting(many endangerd) animals, the pollution of the air and the seas
- I mean I could go on if you want
- no, no, I understand what you are saying and yes .it is true that  there are several problems worldwide caused by human influence
- I think the destruction of amazon rainforest is really dangerous, and it is some thing we could leave(live(✔)) to regred([[file:2020111916-regret.org][regret]](✔)).
- I read somewhere that they were considered to be the lungs of the planet. and there we are happily chopping it all down.
- and it would be a shame to lose some of those animals that may become extinct, you know like the [[file:2020111915-rhino.org][rhino]] or the panda
- but I dont think we shoudn't interfer with nature.
- if they are going to be coming(becomme) extinct then we have to allow nature to take its caulse(course).
- you have just contradicted yourself in two sentences, cathy, first you said it is bad that we are interfering with nature by destroing the rainforest and then. 
- that is not the same thing
- well,ofcoures it is. the only reason 99 percent of these animal are endangerd is precisely becaulse we are threatening their habittats([[file:2020111916-habitats.org][habitats]])
- eighter by [[file:2020111916-chopping.org][chopping]] it down as you said(say) or by expanding towns and farming into areas where these animal normally live and hunt.
- you cant destory (an) animal's habitat and (then) turn aroud and said we can't [[file:2020111916-interfere.org][interfere]] with nature to save them(it).
- I don't think having twenty +pound caps+ panda cubs in zoos aroud the world is a very smart way to save +the+ a animal
- It is totally artificial and is crude to animals invovled
- I would go along with that, the real 
** 19-8-minilecture(3)
- here is what we find on dominance hormone.
- from their baseline when +them+ they come in , high power people experience about a twenty percent increase, ~and~ low power people experience abot a ten percent decrease.
- so again, two minuites and you +got+ get these changes.
- concerning stress hormone, high-power people experience about ~a~ twenty five percent decrease and ~the~ low-power people experience about 15% increase.
- Once again, two minutes +led+ lead to those hormone +not+ changes, that +can figures+ configure your brain to basiclly be +ever+ eigther +asative+ [[file:2020112115-assertive.org][assertive]] confident or really +active+ stress-reactive, +you know or and+ and you know feeling a sort of +shutdown+ shut down.
- and we all have that feeling right
- so it seems that +we worribles+ our [[file:2020112116-nonverbals.org][nonverbals]] do govern how we think and feel about ourselves
- also our bodies change our minds.so
- so power +paulsing+ posing for ~a few~ minuites really +change+ changes your life +for+ in meaningful ways.
- when I tell people about +these+ this, that our +body changes+ bodies change our +mind+ minds and our minds can change our +behaviors+ behavior
- and ~our~ behavior can change our outcomes they +said+ say to me i dont believe that. it feels fake right so i said fake it till u make it.
- I am going to live you with +these+ this
- before for you go in to the next stressful evalutataive situation for example a job interview +do this with two minutes+ for two minutes try +to do+ doing this.
- in the elevator or +the+ at your desk behind the +close+ closed door, and say to yourself +that+ that's what I want to do
- configure your brain to do the best in that situation
- get your dominance hormone up and get your stress hormone down
- dont leave that situation ~feeling~ like oh I +don't+ didn't show them who I am
- leave that situation +to say+ feeling like oh I really managed to say who I am and show +them+ who I am
- to sum up today we  talked abot the [[file:2020112116-nonverbals.org][nonverbal]] expression of power and  dominance and stress  and the +power+ stronng +infacts benefit to change t+ effects of ~the~  +changing+ change of +our+ +behaviors+ behavior
- I suggest you try power posing which is simple. but  will significant change the outcome of your life
- ok next time we are going to discuss the social functions of body language

** 19-8-minilecure(1)
- Body Language and Mind
- Good morning, everyone.
- In today's lecture, I'd like to focus on how our body language ~reveals~ who we are.
- We're really fascinated with body language, and particularly interested in other people's body language.
- You know, we're sometimes interested in an awkward interaction, or a smile, or a [[file:2020112117-contemptuous.org][contemptuous]] glance, or maybe a very awkward [[file:2020112117-wink.org][wink]], or handshake.
- So what kind of body language am I talking about?
- I am interested in power dynamics -- that is the nonverbal expressions of power and dominance.
- And what are nonverbal expressions of power and dominance?
- Well, this is what they are.
- In the animal kingdom, nonverbal expressions of power and dominance are about expanding.
- So you make yourself big, you stretch out, you take up space and you're basically opening up.
- And... and humans do the same thing.
- So they do this when they're feeling powerful in the moment.
- And this one is especially interesting because it really shows us how universal and old these expressions of power are.
- For example, when ~athletes~ cross the finish line and ~they've won~, it doesn't ~matter if~ they've never seen anyone do it. They do this.
- So the arms are up in ~the V sign~, the chin is [[file:2020112117-slightly.org][slightly]] lifted.
- But what do we do when we feel powerless?
- We do exactly the opposite. We close up. We make ourselves small.
- We don't want to [[file:2020112117-bump.org][bump]] into the person next to us.
- And this is what happens when you put together high and low power.
- So what we tend to do when it comes to power is that we complement the other's nonverbals.
- What I mean is if someone is being really powerful with us, we tend to make ourselves smaller.
- We don't mirror them. We do the opposite.
- I'm watching this behavior in the classroom, and guess what I have noticed.
- I notice that [[file:2020112117-mba.org][MBA]] students really ~exhibit~ the full range of power nonverbals.
- They get right into the middle of the room before class even starts, like they really want to occupy space.
- When they sit down, they're [[file:2020112117-sort_of.org][sort of]] spread out. They raise their hands high.
- You have other people who are [[file:2020112117-virtually.org][virtually]] collapsing when they come in.
- As soon as they, I mean other people, come in, you see it.
- You see it on their faces and their bodies, and they sit with their chairs and they make themselves tiny,
- and they will not fully stretch their arms when they raise their hands.


* [[file:2020-10-30.org][2020-10-30]]
1. [[file:2020110313-competen.org][competen]]
2. [[file:2020110313-promises.org][promises]]
3. [[file:2020110313-enrichment.org][enrichment]]
4. [[file:2020110313-discourse.org][discourse]]
5. [[file:2020110313-anecdote.org][anecdote]]
6. [[file:2020110313-convince.org][convince]]
7. [[file:2020110313-distortion.org][distortion]]
8. [[file:2020110313-peculiarity.org][peculiarity]]
9. [[file:2020110313-cultivate.org][cultivate]]
10. [[file:2020110313-spinning.org][spinning]]
11. [[file:2020110313-stripes.org][stripes]]
12. [[file:2020110313-dissertation.org][dissertation]]
13. [[file:2020110313-aesthetics.org][aesthetics]]
14. [[file:2020110313-adhere.org][adhere]]
15. [[file:2020110313-cumulative.org][cumulative]]
16. [[file:2020110313-narrow.org][narrow]]
17. [[file:2020110314-arctic.org][arctic]]
18. [[file:2020110314-hover.org][hover]]
19. [[roam:celcius]]
20. [[roam:stunning]]
21. [[roam:indeed]]
22. [[roam:penetrate]]
23. [[file:2020110314-pace.org][pace]]
24. [[file:2020110314-indigenous.org][indigenous]]
25. [[file:2020110314-ecosystem.org][ecosystem]]
26. [[file:2020110314-dose.org][dose]]
27. [[file:2020110314-finite.org][finite]]
28. [[file:2020110314-demanding.org][demanding]]
29. [[file:2020110314-depleted.org][depleted]]
30. [[file:2020110314-refuel.org][refuel]]
31. [[file:2020110314-admit.org][admit]]
32. [[file:2020110314-abundant.org][abundant]]
33. [[file:2020110314-perception.org][perception]]
34. [[file:2020110314-niece.org][niece]]
35. [[file:2020110314-disruption.org][disruption]]
36. [[file:2020110314-academia.org][academia]]
37. [[file:2020110314-assess.org][assess]]
38. [[file:2020110314-loan.org][loan]]
39. [[file:2020110314-sustainable.org][sustainable]]
40. [[file:2020110314-visionary.org][visionary]]
41. [[file:2020110314-campaign.org][campaign]]
42. [[file:2020110314-locomotive.org][locomotive]]
43. [[file:2020110314-compound.org][compound]]
44. [[file:2020110314-crisis.org][crisis]]
45. [[file:2020110314-accommodation.org][accommodation]]
46. [[file:2020110314-subsidized.org][subsidized]]
47. [[file:2020110314-expectancy.org][expectancy]]
48. [[file:2020110314-diminished.org][diminished]]
49. [[file:2020110314-irregullar.org][irregullar]]
50. [[file:2020110314-inadequate.org][inadequate]]
51. [[file:2020110314-dwell.org][dwell]]
52. [[file:2020110314-predators.org][predators]]
53. [[file:2020110314-threat.org][threat]]
54. [[file:2020110314-vaccinate.org][vaccinate]]
55. [[file:2020110314-extinction.org][extinction]]
56. [[file:2020110314-shepherd.org][shepherd]]
57. [[file:2020110314-herd.org][herd]]
* [[file:2020-11-16.org][2020-11-16]]
1. [[roam:roughly]]
2. [[roam:comprising]]
3. [[roam:assertion]]
4. [[roam:matter]]
5. [[roam:stretch]]
6. [[roam:machinery]]
7. [[roam:cruise]]
8. [[roam:telomeres]]
9. [[roam:centromeres]]
10. [[roam:susceptibility]]
11. [[roam:biallelic]]
12. [[roam:susceptbility]]
13. [[file:2020112021-approximately.org][approximately]]
14. [[roam:phenotypic]]
15. [[roam:alterrations]]
16. [[roam:monozygotic-twins]]
17. [[roam:conundrums]]
18. [[roam:epigenetics]]
19. [[roam:resemble]]
20. [[roam:beads]]
21. [[roam:residues]]
22. [[roam:undeniably]]
23. [[roam:intricacies]]
24. [[roam:repress]]
25. [[roam:cleavage]]
26. [[roam:exquisitely]]
27. [[roam:palindromiic]]
28. [[roam:viability]]
29. [[roam:orgnalles]]
30. [[roam:synthesized]]
31. [[roam:cytosol]]
32. [[roam:catabolize]]
33. [[roam:repertoire]]
34. [[roam:orchestrated]]
35. [[roam:epithelia]]
36. [[roam:synthesis]]
37. [[roam:Phosphatidylinositol]]
38. [[roam:electrostatic]]
39. [[roam:scaffold]]
40. [[roam:passive]]
41. [[roam:nutrient]]
42. [[roam:disposal]]
43. [[roam:osmotic]]
44. [[roam:swelling]]
45. [[roam:lattice]]
46. [[roam:invagination]]
47. [[roam:pinches]]
48. [[roam:intertwine]]
49. [[roam:elongating]]
* [[file:2020-11-19.org][2020-11-19]]
[[*19-8-interview(2)][19-8-interview(2)]]
[[*19-8-interview(1)][19-8-interview(1)]]
* [[file:2020-11-20.org][2020-11-20]]
- [[file:2020112015-harmony.org][harmony]]
- [[file:2020112015-peace.org][peace]]
- [[file:2020112016-hello.org][hello]]
- [[file:2020112016-hope.org][hope]]
- [[file:2020112015-wonderful.org][wonderful]]
- [[file:2020112016-refuge.org][refuge]]
- [[file:2020112016-doom.org][doom]]
- [[file:2020112017-finally.org][finally]]
- [[file:2020112017-heaven.org][heaven]]
- [[file:2020112017-what.org][what]]
- [[file:2020112017-involution.org][involution]]
* [[file:2020-11-21.org][2020-11-21]]
- [[*19-8-minilecture(3)][19-8-minilecture(3)]]
