#+title: 2020-11-27

* 前言
乡野村夫才疏学浅,昨天只能送大家一份小礼物,如果能帮大家多背几个考研单词,是我的荣幸哟. 观想着差不多刚好还有一个月,看着b站上面很多考研儿说这段时期很苦很累压力巨大还心态又爆炸,我忽然眼前一亮,不禁说出一句"我去!专业这么对口!!!去病除苦这不是我的专业和天职嘛,B站上那些说累说苦的是不是因为没得我这样的医学生朋友",因为我的大学同学们呀也正在精进的准备着六级和期末考试. 而我作为一个赋闲在家的医学生嘛就当仁不让的站出来发挥下专业特长吧,顺便也想作为之前大家对我关心守护的回礼,一箭双雕这波我不亏甚至是血赚呢,哈哈哈哈哈.
回个什么礼呢,大家说现在又累又苦,累嘛因为每天都在高负荷的学,况且人尽皆知一分耕耘一份收获嘛,不劳而获这种事嘛除了痴人白日做梦和怪力乱神的邪见妄见我想不出第三个了.作为马克思主义的坚定信仰者,高举红旗相信英特纳雄耐尔一定能实现的考研儿们当然是不屑于顾那一套的.那么对于累,我也没得啥法了,no pain no gain嘛. 那么说到苦,我去!!!这玩意儿我懂啊(此时模仿一下我川宝:No one can know it better than me!),我观想了下能送大家个什么武器去降服它呢,要不把它伪装成做个小游戏的形式?我感觉不错,有点创意,那这个游戏的名字就叫"按F进入贤者模式吧",我又观想发明着就像喜欢在网吧玩游戏一样,图的是个氛围嘛,那什么时候和大家玩这个游戏好呢,深夜吧,大家应该都在收拾收拾准备休息,有时间而且晚上氛围也适合进入贤者模式,那我就晚上11点发朋友圈吧.
* bilibilibili游戏模式启动
那让我先试试这个游戏怎么玩哈
第一步系统提示说是要选择信仰,候选项有(马列主义和毛泽东思想,佛教,道教,伊斯兰教,基督教...), 这个我怕你们乱选影响考研政治答题哈,我用root权限锁定马列主义毛泽东思想了. 第二步嘛系统说叫选择特殊能力说是(像王思聪那样的富二代,像博瓜瓜那样的官二代,像sadhguru那样的瑜伽大师),我想着这个也怕你们乱选,而且瑜伽嘛肯定会静坐和冥想嘛,我想着中国儒释道三家赞助商都推荐冥想作为武器,那就选它吧,更现实而且更广泛和易用,第三步说是选择性别(这个我选男的了),诸君自己抉择了吧
* 系统提示所有环境变量都以初始化完成,请按F进入
好那我们就在马列主义唯物辩证的方针下来思惟发明吧,因为进入贤者模式了就用书面点的口吻了哟.
恩格斯如是说:"近代哲学的重大的基本问题,是思惟和存在的关系问题,我们的主义认为物质是第一性的"又说"同时我们也坚信思惟是能够认识存在的,即具有同一性"正因为具有同一性哈,我们的思惟发明游戏才有继续下去的意义哈,不然的话岂不是真成了不会开花的树?"
好那我们就从物质和意识的两个角度,剖析考研儿们的苦吧.我们就把苦分为物质上的苦和意识上的苦(其实用更精确的语言苦这个词应该是一种感觉,物质上的苦不太准确,但是人身体上的不舒服和意识范畴中苦的生,住,灭几乎是同时的(simultaneous,友情送个单词别到时候不会哈))
** 物质上的苦
物质上的苦主要是身体上的吧, debuff还有点多, 天气冷, 意识上压力大导致晚上睡不好, 神经系统和内分泌系统多少会受点影响, 严重了的话消化系统也会出现问题.
那么我们有什么方法降服呢?
*** 针对天气冷
多听爸爸妈妈的话,衣服穿够
*** 针对胃肠功能减低
**** 试试晨起,或者饭后一到两小时后4-8公里/h的时的速度慢跑30分钟?
别饭后一会儿就去跑,胃里东西太多又跑容易胃下垂
**** 可以喝喝温水暖暖?
**** 可以用手揉揉?
**** 可以吃点健胃消食片?
**** 作为唯物主义者你可以永远相信医生
*** 针对晚上睡不好
**** 规律的作息时间?
- 大家都知道人是有生物钟的,古人尚道日出而作日落而息.人体的内分泌系统和神经系统的化学抵制的分泌也存在着一定的规律,如果违背了这些规律容易出现一些功能紊乱,引起相应疾病
**** 听听音乐或者白噪音?
- 我平常喜欢听网易云里面的纯音乐,或者(我个人而言)
- 白噪音推荐有个app叫潮汐(英文名叫tide(又友情送一个单词哦))
**** 睡前少看手机?
- 之前告述过周俸嘉有个由松果体分泌的叫做褪黑素的激素,对光刺激比较敏感,同时又对昼夜节律和改善睡眠质量比较重要.但是千万别百度后看着什么有代购叫你吃激素的,千万别买着吃啊,容易出大问题.
**** 或者试试使用特殊技能冥想?
- 睡前闭上眼睛躺在床上,放空转了一天的大脑,慢慢的将注意力放在呼吸上,虽然意识中涌动着许多思绪,你就让它们飘过吧,不要像白天一样用你的专注去抓住它们捏着不放,不要去攀援,不要去执着.只要你的呼吸很平静,有规律,任由思潮涌动都不再理会,慢慢的,慢慢的,你就发现天亮了(我之前反正很容易睡着).
** 程序warning:马列主义意识领域阐述不足是否引入外援?"引入外援将降低程序健壮性,容易导致理论大厦坍塌"
因为我自己的信仰是沿着觉者乔达摩悉达多给我指的路,我确信它是与马列主义完全兼容的,但是我不排出一千个读者就有一千个哈姆雷特,我想表述的不是你们所接受的.诸君都是善知识有大慧根之人,懂得如何哲学思辨与扬弃.所以我选择将我将走的路也展示给诸君任诸君取舍.
** 程序:社会主义和谐版佛教资源加载中,相关资源文件已加载
*** 名词解释
因为2500年来斗转星移,很多业力累计产生许多偏见邪见,因为这些邪见妄见通过他人言说,往往是我们在接触一些事物之前已经在脑中有了对它的定性定义.所以我选择将一些我们中华文化中容易引起大家心中的先入为主,观念的词语换掉,避免影响大家的思辨
**** Buddha 觉悟的人 (汉译佛陀,常诱发妄见但是是正确的词汇:"如来佛祖","佛祖")
**** 菩提萨埵 (此处直接取汉音译"菩萨"的全称,菩提萨埵)
**** samadi 禅定(三摩地)
**** 阿缛多罗三渺三菩提 无上正等正觉
*** 因缘分
- 因众因缘,故有我
- 因有我及众因缘,故有我识诸君
- 因有我及众因缘,故有我从医
- 因我从医及众因缘,故我有此际遇
- 因有此际遇及众因缘,故我作此文
*** 降服面对未知时的,抑郁,紧张,恐惧,焦虑.面对失败时的害怕,面对无常时的无力.降服封建迷信怪力乱神.降服生,死.
**** 我选择以散文的方式向大家展示一番美景
当我们有着这样或者那样的因缘,让我们知道我们应该重视自己情绪管理,因为在我们脑海中生生灭灭的各种观念想法啊,他们变化无常,不时的出现,一不注意就被我们的专注所捕获,在我们的脑海中萦绕啊.徘回啊,可能一会儿就消失?又或是好长时间才结束.当这些生生灭灭的想法是积极的,乐观的?我们可能会开心啊好长时间.当这些观见想法判断是消极的,我们可能会啊一整天都闷闷不乐.但是乔达摩悉达多觉者,通过他在冥想中得到的感悟,告诉我们:"或许我们可以不再被这些生生灭灭的想法所驱使?或许我们拥有这样的能力控制它们让它们随着我们而动?",乔达摩悉达多觉者又说:"冥想是我们的武器,通过冥想我们可以训练自己的意识活动,让这些时时刻刻生灭无常的观念想法啊,虽然仍然生灭,但是不被我们我们内心所攀援留住".于是啊我们选择相信乔达摩悉达多觉者的话,万一他说的是对的呢?我们开始通过冥想来训练自己的意识,首先我们轻闭着双眼或者微微张开,双目可以看着前方或者随你舒服?当你有着要控制攀援这些生灭观念想法的时候,你应该知道实际上你已经默认了这些生灭的观见想法啊不属于你心中所认为的,执着的那个"我".好让我们试着继续做下去,首先你可能会觉得脸部肌肉有点紧绷?那我们试着放松它.头上似乎也有点?我们也放松一下.但是在这个过程中呀,请保持你的呼吸,均匀且规律,虽然我们有着这样的觉知或者那样的觉知,我们眼前可能会浮现着这样的或那样的物品,人物,事件?没关系,它们本来就是生灭的,我们不去攀援停驻就行.或许,一会儿,你会觉得平时没有听见的声音听的更清楚了?或许,一会儿你的眼前浮现出来了汹涌的潮水?咦你好像看清潮水上的泡沫!耳旁也好像听见了潮水的声音了!!!忽然一会儿你又看见了风吹的麦浪,再随着风轻柔的飘摇呀飘摇呀.你好像觉得自己的呼吸有点加深了些?好像身体释放点压力?没错,不如我们再接着欣赏下去?或许,一会儿你好像因为身心的完全放松而察觉到了什么,你好像察觉到了在你脑海中生生灭灭的这些观念啊图像啊好像有着一种共同的东西,说它是东西呢?好像不太对,它好像并不是物质世界的各种现象在我们脑海中的投影,它并没有大小或者形状.但是你明明又能感觉到它的存在.我这里说它?好像不太对,因为它呀好像存在于你所能认知的觉察的所有东西之中,但是你看呀你所知道那些物质世界的各种投影呀,分子原子?磁场电场?好像都与你意识中的那些生灭的观念想法啊有着同样的性质,它们都是因为这样或者那样的条件,原因所成就了它们在你脑中停留的样子?在物质世界表现的形式?但是好像刚刚我们所感受到的那种被称为"东西"的东西,好像并没有生灭的性质.它好像一直就在那,只是因为你之前好像一直把你的注意力啊放在了那些你脑袋中生生灭灭的观念想法之中,一直没注意它的存在.因为它好像一直在那儿,在你生灭的观念中,在那些物质世界客观存在的原子分子中,磁场电场中,在你血管中.不对啊!!!我怎么感觉它哪儿都有啊!!!你说它是一呢好像不圆满,为什么呢,如果没有异,一没有意义啊.你说它是异吧也不对,它明明哪都有啊!那它到底是一,还是异?是不一,还是不异???等一下,我们为什么要执着于它到底是一还是异?我们为什么一定要以是非,对错,美丑,善恶,好坏,生死这样的一对对矛盾来定义定性它?我们是不是又在执着于什么东西?我们刚刚不是说好了不执着吗?好那我们姑且说它不一也不异.因为啊我们不再执着是非,对错,美丑,善恶,好坏,这样一对对的矛盾中.我们就姑且叫他中道???好那我们继续下去因为它好像一直在那,遍布四方上下,我们不能说它会灭,为什么呢,因为我们不是说好了不以边见定义东西了吗,因为它根本就一直在那从来没有出现过生,怎么又会有灭呢?啊?有种东西不生不灭?那我得到它岂不是可以长生不老?哈哈哈咱都到这个地步了你还在乎生死吗?在你的意识范围内中有一种叫做"我"的东西,"我"它以为它是它的生灭的肉体,它漂亮或者衰拜的容颜,它胖瘦的身体,它高低的鼻梁.正是由于呀,以前它不明白这个世界的真实面目,所以我们姑且把此称为无明吧.因为它执着追求于生,美,高,瘦的种种生灭现象,厌恶于死,丑,矮,胖的种种生灭现象,所以它被意识中的那些喜爱啊,厌恶啊,积极呀乐观的情绪所阻碍.它并没有发现在这广阔山河,天清阔宇中有着一种姑且称为存在的存在吧,存在于它所认为的属于它的肉体中,它并没有意识到其实它本来就有着不生不灭,不一不异,不能由种种矛盾所定义的,不能以肉眼见,不能以耳听(故佛曰:不可说),不能以身触,不能以鼻闻,不能以舌尝,不能以专注去攀援停驻的某种尚且称为东西的东西(故佛云:不可思议).这种东西好像从来没有来过,又好像从来从来没有消失.我们姑且呈之为如来吧,'我'有如来,你有'如来',他也有'如来',它也有'如来',乔达摩悉达多有如来但是他好像是我们所知道的第一个能证悟到这种东西存在的人吧?我们姑且叫他什么什么祖吧,那什么什么祖呢?梵语说是buddha,音译的话?不它?不好听!那用什么呢如,好像,好像,仿佛,仿佛,佛,佛陀!!!就叫佛陀!!!那它就叫佛祖吧!!!等下让我们又回到刚刚观想的如来不是在我们这四方上下,澄清宇宙中吗.对,所以我们称乔达摩悉达多觉者为佛祖,因为在姑且称为"他"的生灭身体灭度后啊,还有我们一个又一个的具有如来,具有佛性的种子等着盛开绽放呢,所以我们是佛陀二号,佛陀三号,Buddha 2号,Buddha 3号,觉悟的人2号,觉悟的人三号.不管你取什么名字,都可以,都符合乔达摩悉达多觉者告诉我们的真理.生而为人,能得证悟成佛,不是一你认为的"幸福"嘛,所以为什么要看太宰治那个在六道轮回里沉溺的人.
**** 你上面扯的那些有的没的是我天天烧香拜的那玩意儿说的嘛?
- 如果你同意乔达摩悉达多觉者就是我们所烧香拜佛拜的那个玩意儿,那他说过这么一句话:诸法无我(所有种种事物啊都是无我的,及是生灭的),诸行无常,涅磐寂静这三点是我承认是不是我说的话的印章.
- 所以我上面所写的那些文字啊被你天天烧香拜的那玩意儿承认是他说的
**** 即使你说的是对的那又如何呢?
- 不如何呀,你并没有因此而少什么东西,也并没有因此而多什么东西.所以不如何呀
**** 你说的那些东西不能被证实也不能被证伪啊?
- 对,因为如人饮水冷暖自知.你只能通过冥想去证悟.而你所得到的证悟只对你自己有用,因为只有你相信那是这个世界的真实面目.当你通过任何形式告诉任何有自我意识的有情,它也会问你曾经问过的问题.而你又得告诉它你自个儿悟去吧!当你忽然发觉,这尼玛是个死循环啊,爷不在这个轮回里面玩了!!!好恭喜你,乔达摩悉达多把你这种有自我意识的有情称为罗汉.如果一个有情到了你这个级别呢就叫到了罗汉果位.有个叫观自在老几头铁的很,他说这不行啊,虽然我证悟了但是还有那么多有情在懵逼着呢原地绕圈呢,我得帮帮它们呀.乔达摩悉达多说:哟,这儿来了个思想觉悟有点高的.那你这个级别的就和刚刚那个区别开吧,你这个级别的就叫菩提萨埵吧,你这个格局比上一个大,那你这个就叫走大路吧,他那个就叫走小路.(故有大乘,小乘之分)
**** 那你扯了些有的没的假大空啊,方法论,我TM现在压力大的要死,天天焦虑啊担心啊害怕啊,都tm想跳楼或自杀了!!!
- 好好好,我们先冷静冷静.你觉得我上面说的是世界的本来面目不?是或者不是?或者将信将疑?等等等等,或者我换个说法你会更容易接受些?你天天转的那些求好运的说说,朋友圈,拜的那些神佛菩萨说:我现在承认上面是我说的,你信不?我想你大概率会信的吧?
- 好假如你信了,但是菩萨们又说这个啊,我们不是什么怪力乱神诶,我们也是普通的人的嘛.我们不会凭空的产生一些东西或者消失一些东西,我们不会让你一下获得一些东西又一下减少一些东西,我们只能告诉你这个世界是什么本来面目.
- 好假如你说,好好行,我求求你了快告诉我,我急得要死啊.
- 菩萨就会说:不是说了嘛这个,就是我上面说的啊,你得自己自己去悟道
- 你会说:我tm现在哪有时间去悟道啊!我tm急得要死啊!!!!
- 菩萨又会说那我说的你都得信哦!
- 你会说:好好,我全都信,全都信!!!
- 菩萨会说:你虽然肉体会变坏,但是你会有灵魂的.如果你自杀了,你的灵魂会在地狱里面承受各种酷刑
- 你会说:我的妈也,我现在还痛苦,死了也痛苦,还不如活着算了!
- 菩萨会说:找到一个活着的理由没得?先把心安在那儿去,来坐下听我.嘻嘻,刚刚其实是骗你的,世界根本没有什么地狱.别自己骗自己了,快回家去,乖,再也不要想自杀这件事了,用剩下的日子去悟道吧!一定要做个好人,精进向上,我们可以享受欢娱但是不要沉溺哦,我们也要允许自己有失败,高于物质和意识的最好的东西既是是又是不是,既不是是,又不是不是的.啥子?听不懂哇,因为听不懂所以要去学嘛,所以要好好的生活去悟道嘛,现在你是不是觉得人生有目标,有意义了嘛.去吧去吧,快去吧,快到彼岸去吧!
