#+title: 伦理学

* 前言
从2019年末于武汉爆发的covid-19全球大流行一直持续至今,但是在中国共产党强有力而明智的领导下,全国上下一盘棋,从武汉封城到全国人民居家隔离,中国以其高度组织力和团结力对新冠病毒做出了强有力的一击. 也正是如此,使得爆发的疫情对医疗系统的冲击降到最小,避免了出现在西方的因为短时间出现大量感染者超出医疗系统极限而被迫作出稀缺医疗资源分配的伦理选择难题.

* 各国呼吸机分配伦理原则概述
** 美国
- 作为唯一的超级大国,美国拥有着世界上最好的医疗资源. 即使如此,在美国的资本主义制度以及小政府的理念下,全美各地各自为战,政府对于社交娱乐活动限制不足,导致感染人数呈现井喷式爆发.使得美国医务人员处于不得不给病人做生死排序的两难境地.也正因此种社会制度,美国不同州关于呼吸机的分配标准也各不相同.
  1. 纽约州采用的<<纽约州呼吸机分配指南>>, 融合了医学、公共卫生、法律、宗教、哲学和生物伦理学各方面的专家意见。这项方案里，评估的关键是按器官顺序评估衰竭打分，医生必须衡量了六个关键器官和系统的功能。该准则规定，有关呼吸机分配的决定绝不应基于非临床因素，例如种族、性取向、社会经济地位、生活质量、支付能力或在社会中的作用。该客观方法被认为在遵守重要社会价值的同时，是增加幸存者人数的最佳方法.它的道德框架基于如下原则：
     - 护理义务：尊重医疗服务提供者照料患者的基本义务。
     - 管理资源的责任，制定计划的责任和正义的分配：通过在紧急短缺时提前设计合理的呼吸机分配系统来防止不平等状况的发生。
     - 透明：在医疗保健提供者、患者、患者家属和公众之间进行清晰一致的沟通。
  2. 约翰霍普金森和梅德斯达在内的美国百家医院采用的由匹兹堡大学医学中心（UMPC）的危重病医学教授道格拉斯·怀特博士开发的框架.本质是一个计算病人从重症护理中受益的可能性的积分系统，主要基于两个考虑因素：1）最大限度地挽救生命；2）最大限度地挽救存活年限。这是一个8分值量表：前4分说明患者住院生存的可能性；后4分评估假如患者住院治疗，与之匹配的预期寿命小于一年或小于五年的相关医疗条件。得分越低的，也就是说活得长且消耗医疗资源较少的，这类患者在这套框架下得到重症护理的优先顺序就越靠前。简单说，谁占的医疗资源少，救治后又可以活得比较长，那就会先救治谁。当然，平均情况下，怀特博士的这个框架指导医生们考量生命周期，即优先考虑年轻患者。
     但是在实施的过程中却各州都出现了“排除标准”,包括创伤性脑损伤、严重烧伤、严重痴呆、肌萎缩侧索硬化和终末期多发性硬化患者；还有的州把一些高龄、重度认知障碍、慢性心肺疾病患者均排除在优先救治顺序之外.
     
** 欧盟
- 欧盟与美国同样作为经济与医疗资源发达地区,因为其政府在新冠大流行期间的表现欠佳,导致其医疗体系受到较大冲击.因此其医务人员同样面临此两难局面
  - 法国斯特拉斯堡大学医院因医疗能力不足，不再给80岁以上处危重状态的病人吸氧，而是使用助眠产品和镇静药物进行“姑息疗法”。所谓姑息疗法，指的是仅为病人减轻痛苦，并给予临终关怀。
  - 西班牙的医生不得不选择拔掉65岁以上老人的呼吸机，让更多的年轻人或者有更高社会价值的人得到救治。
  - 意大利是欧洲疫情最严重的国家，医院很快就被病人挤满，并且很多都是老年人的危重患者。意大利也采取了同西班牙一样的措施，医生不得不做出艰难的抉择，选择治疗哪些人，放弃哪些人，这背后残酷的事实是缺乏足够的呼吸机。
  - 德国7个医学协会通过一项“生死指南”，指出病人在经过重症治疗后存活的几率将是医生考虑的主要因素，最终的决定将由三位来自不同医学领域的专家共同做出。指南写道，新冠病症的严重程度、次要疾病以及患者的意愿也是考虑因素，但年龄和社会地位不在考虑之列。

** 中国
- 从一开始我国对抗疫情的表现就与国外形成了鲜明对比,从西方公布的医疗系统排名我国并不占优势.但是我国得益于优越的社会制度.在党的领导下,执行"应收尽收,不漏一人"的方针,同时针对全民由国家承担新冠治疗费用,修建火神山雷神山等医院,使得患者都得到医治和隔离,大大的限制了病毒的传播.
- 由于我国是制造业第一大国,加之我国疫情控制较好,虽然在疫情早期出现医疗资源紧缺现象但未发生像西班牙与意大利似的医疗系统崩溃.

* 总结
- 西方各国基于年龄而"拔管"的医疗行为可能出于以下几种伦理辩护
  - 功利主义：拯救更多生命功利主义论证认为，医疗资源依年龄分配的结果应当符合功利主义原则，即从长远看有利于提升大多数人的总体利益。既然年轻人通常有更长的未来生命预期，以及更高的生产效率，因而医疗资源分配应当向年轻人倾斜
  - 自由主义: 捍卫机会平等.认为年龄分配并不一定意味着年龄歧视。年龄与性别、种族不同，它不属于个体不变的特征，而是随着个体生命阶段的改变而变化。因此自由主义倾向于保护个体达到正常寿命的机会,实现机会平等.
  - 社群主义:年人接受衰老与死亡的最大动因是一种代际延续的明确自觉：要让年轻人蓬勃发展，老年人就应主动退居一边，直到生命行将结束，并要努力为后人留下一个充满希望和馈赠的世界。
- 首先,我们必须得承认,呼吸机分配伦理原则这一难题建立在医疗资源严重不足的情况下.在这种状态下无论作出何种选择,例如将70岁以上老人"拔管",这种选择本身就是一种悲剧.所以我们所能采取的最佳措施是一开始就防治这种事情发生.这要求我们建立完整的疫情防治体系,在平时做好一定数量的资源储备,但是最关键的是在疫情爆发后以人为本,防治疫情的扩散而不是像西方国家那样以资本为本.
- 其次深受儒家文化熏陶的新中国,爱老敬老的中国人,绝对不会把牺牲老年人的医疗资源作为合理的解决方法. 
