#+title: English Listening Skill

* 19-8-interview(2)
- [[file:2020111910-disciplinary.org][disciplinary]]
- [[file:2020111910-literacy.org][literacy]]
sciplinary literacy (学科素养)
- [[file:2020110313-convince.org][convince]]
- [[file:2020111911-affiliation.org][affiliation]]
- [[file:2020111911-assessment.org][assessment]]
- [[file:2020111911-interpreting.org][interpreting]]
- [[file:2020111911-sophisticated.org][sophisticated]]
- [[file:2020111911-weigh.org][weigh]]
- [[file:2020111911-engage.org][engage]]
  
* 19-8-interview(1)
- hey cathy did you read this article in this magazine?I cant believe how much man is changing the planet.
- yeah I had a look at it, quite intresting I suppose if you believe that sort of thing
- what? what do you mean if you believe that sort of thing
- are you saying you dont believe that we are damaging the planet?
- to be honest mark, not really
- what do you saying, are you saying global warming isn't a fact, deforestation isn't a fact, the greenhouse effect isn't actually happening?
- hey calmdown mark, I just think too many people take these things as been(❎) being(✔) definitely true without knowking all the facts
- you really dont think global warming is happening
- you know they have said sea levels are going to rise by quite a few meters over the next fifty to a hundread years
- wheather conditons are getting worse all over the world
- can you remember how many big hurricanes there have been in the country over the last few years
- I think evidence is around us
- I dont think we have enough infomation to be honest, we have only being measuring these things for around two or three hundread years
- we have no idea what was happening fifty thousands years ago.
- for all we know this is just a natural [[file:2020111916-blip.org][blip]], a kind of sudden but temperary change, in the whole climate cycle
- I dont think we should change how we living just because of twenty years of abnormal measurements.
- and dont you think all the other effcets we are having on the planets are destructive?
- and what do you mean?
- I mean like deforestation,overpopulation,threatening the existence of extincting(many endangerd) animals, the pollution of the air and the seas
- I mean I could go on if you want
- no, no, I understand what you are saying and yes .it is true that  there are several problems worldwide caused by human influence
- I think the destruction of amazon rainforest is really dangerous, and it is some thing we could leave(live(✔)) to regred([[file:2020111916-regret.org][regret]](✔)).
- I read somewhere that they were considered to be the lungs of the planet. and there we are happily chopping it all down.
- and it would be a shame to lose some of those animals that may become extinct, you know like the [[file:2020111915-rhino.org][rhino]] or the panda
- but I dont think we shoudn't interfer with nature.
- if they are going to be coming(becomme) extinct then we have to allow nature to take its caulse(course).
- you have just contradicted yourself in two sentences, cathy, first you said it is bad that we are interfering with nature by destroing the rainforest and then. 
- that is not the same thing
- well,ofcoures it is. the only reason 99 percent of these animal are endangerd is precisely becaulse we are threatening their habittats([[file:2020111916-habitats.org][habitats]])
- eighter by [[file:2020111916-chopping.org][chopping]] it down as you said(say) or by expanding towns and farming into areas where these animal normally live and hunt.
- you cant destory (an) animal's habitat and (then) turn aroud and said we can't [[file:2020111916-interfere.org][interfere]] with nature to save them(it).
- I don't think having twenty +pound caps+ panda cubs in zoos aroud the world is a very smart way to save +the+ a animal
- It is totally artificial and is crude to animals invovled
- I would go along with that, the real 
  
* 19-8-minilecture(3)
- here is what we find on dominance hormone.
- from their baseline when +them+ they come in , high power people experience about a twenty percent increase, ~and~ low power people experience abot a ten percent decrease.
- so again, two minuites and you +got+ get these changes.
- concerning stress hormone, high-power people experience about ~a~ twenty five percent decrease and ~the~ low-power people experience about 15% increase.
- Once again, two minutes +led+ lead to those hormone +not+ changes, that +can figures+ configure your brain to basiclly be +ever+ eigther +asative+ [[file:2020112115-assertive.org][assertive]] confident or really +active+ stress-reactive, +you know or and+ and you know feeling a sort of +shutdown+ shut down.
- and we all have that feeling right
- so it seems that +we worribles+ our [[file:2020112116-nonverbals.org][nonverbals]] do govern how we think and feel about ourselves
- also our bodies change our minds.so
- so power +paulsing+ posing for ~a few~ minuites really +change+ changes your life +for+ in meaningful ways.
- when I tell people about +these+ this, that our +body changes+ bodies change our +mind+ minds and our minds can change our +behaviors+ behavior
- and ~our~ behavior can change our outcomes they +said+ say to me i dont believe that. it feels fake right so i said fake it till u make it.
- I am going to live you with +these+ this
- before for you go in to the next stressful evalutataive situation for example a job interview +do this with two minutes+ for two minutes try +to do+ doing this.
- in the elevator or +the+ at your desk behind the +close+ closed door, and say to yourself +that+ that's what I want to do
- configure your brain to do the best in that situation
- get your dominance hormone up and get your stress hormone down
- dont leave that situation ~feeling~ like oh I +don't+ didn't show them who I am
- leave that situation +to say+ feeling like oh I really managed to say who I am and show +them+ who I am
- to sum up today we  talked abot the [[file:2020112116-nonverbals.org][nonverbal]] expression of power and  dominance and stress  and the +power+ stronng +infacts benefit to change t+ effects of ~the~  +changing+ change of +our+ +behaviors+ behavior
- I suggest you try power posing which is simple. but  will significant change the outcome of your life
- ok next time we are going to discuss the social functions of body language

* 19-8-minilecure(2)
- I also notice another interesting thing about this.
- It seems women are much more likely to do this kind of thing than men.
- I mean women are more likely to make themselves small.
- Women feel chronically less powerful than men, so this is not surprising.
- The second question concerns our minds.
- We know that our minds change our bodies.
- But is it also true that our bodies change our minds?
- And when I say minds, in the case of the powerful, what do I mean?
- I'm talking about thoughts and feelings and the sort of physiological things that make up our thoughts and feelings,
- and in my case, that's hormones.
- I look at hormones.
- So what do the minds of the powerful [[file:2020112310-versus.org][versus]] the powerless look like?
- Powerful people tend to be, not surprisingly, more assertive and more confident, more optimistic.
- They actually feel that they're going to win even ~at~ games of chance.
- They also tend to be able to think more abstractly.
- They take more risks.
- So there are a lot of differences between powerful and powerless people.
- Physiologically, there also are differences on two key hormones: one is dominance hormone, and the other is stress hormone.
- What we find is that powerful and effective leaders have high dominance hormone and low stress hormone.
- What does that mean?
- That means power is also about how you react to stress.
- Once we did an experiment.
- We decided to bring people into the lab and run that little experiment.
- These people adopted, for two minutes, either high-power [[file:2020112310-poses.org][poses]] or low-power poses.
- We, for two minutes, say, "You need to do this or this."
- And we also want them to be feeling power.
- So after two minutes we will ask them "How powerful do you feel?" on a series of items, and then we give them an opportunity to [[file:2020112310-gamble.org][gamble]].
- Before and after the experiment, we take their samples of [[file:2020112310-saliva.org][saliva]] for a hormone test.
- That's the whole experiment.
- And this is what we have found -- risk tolerance, which is gambling.
- What we find is that when you're in the high-power pose condition, 86 percent of you will gamble.
- When you're in the low-power pose condition, it's down to only 60 percent, and that's a pretty significant difference.
* 19-8-minilecure(1)
- Body Language and Mind
- Good morning, everyone.
- In today's lecture, I'd like to focus on how our body language ~reveals~ who we are.
- We're really fascinated with body language, and particularly interested in other people's body language.
- You know, we're sometimes interested in an awkward interaction, or a smile, or a [[file:2020112117-contemptuous.org][contemptuous]] glance, or maybe a very awkward [[file:2020112117-wink.org][wink]], or handshake.
- So what kind of body language am I talking about?
- I am interested in power dynamics -- that is the nonverbal expressions of power and dominance.
- And what are nonverbal expressions of power and dominance?
- Well, this is what they are.
- In the animal kingdom, nonverbal expressions of power and dominance are about expanding.
- So you make yourself big, you stretch out, you take up space and you're basically opening up.
- And... and humans do the same thing.
- So they do this when they're feeling powerful in the moment.
- And this one is especially interesting because it really shows us how universal and old these expressions of power are.
- For example, when ~athletes~ cross the finish line and ~they've won~, it doesn't ~matter if~ they've never seen anyone do it. They do this.
- So the arms are up in ~the V sign~, the chin is [[file:2020112117-slightly.org][slightly]] lifted.
- But what do we do when we feel powerless?
- We do exactly the opposite. We close up. We make ourselves small.
- We don't want to [[file:2020112117-bump.org][bump]] into the person next to us.
- And this is what happens when you put together high and low power.
- So what we tend to do when it comes to power is that we complement the other's nonverbals.
- What I mean is if someone is being really powerful with us, we tend to make ourselves smaller.
- We don't mirror them. We do the opposite.
- I'm watching this behavior in the classroom, and guess what I have noticed.
- I notice that [[file:2020112117-mba.org][MBA]] students really ~exhibit~ the full range of power nonverbals.
- They get right into the middle of the room before class even starts, like they really want to occupy space.
- When they sit down, they're [[file:2020112117-sort_of.org][sort of]] spread out. They raise their hands high.
- You have other people who are [[file:2020112117-virtually.org][virtually]] collapsing when they come in.
- As soon as they, I mean other people, come in, you see it.
- You see it on their faces and their bodies, and they sit with their chairs and they make themselves tiny,
- and they will not fully stretch their arms when they raise their hands.


* 18-8-interview(1)
- W: Good evening listeners, this is BBC. Today, we are very delighted to have invited James Dobbins, US special [[file:2020112311-representative.org][representative]] for Afghanistan, to tell us the [[file:2020112311-electoral.org][electoral]] process in Afghanistan currently. Well, James, how are you reading what's happening in Afghanistan at the moment?
- M: We're concerned about the trend in ~events~. We ~have been~ concerned for some time that the electoral process ~hasn't~ been moving forward smoothly. We believe there needs to be a powerful and transparent ~audit of~ potentially dishonest ~ballots~ and we're sorry that hasn't moved forward quickly and substantially enough. We regret the [[file:2020112311-preliminary.org][preliminary]] announcement ~of results~ that was made yesterday. We think that~was [[file:2020112311-premature.org][premature]] given that there are still a number of ballots that need to be examined and there's not yet a clear agreement on how best to do so. We do believe that...
- W: Forgive me for interrupting, James. Can~I ask~you why you think that announcement was made yesterday?
- M: I think~it was made because the electoral institutions had ~previously~ set that date and they held to it despite advice to the contrary from the ~UN~, from the United States, and from other voices ~within~ Afghanistan, and we think that was unfortunate.
- W: Is there~another reason that could be slightly more [[file:2020112311-favorable.org][favorable]], that~is, they wanted to prepare the ground because if they just came out* with one final result at the end of all this then it can be pretty likely ~that* the~ loser, whoever it was going to be, was going to complain because they think it is unfair?
- M: I think it's ~our~ view that they didn't have a basis for preparing the ground because there's such a large number of votes that still need to be examined and* ~that~ therefore any [[file:2020112311-preliminary.org][preliminary]] result might be more misleading than preparing the ground.
- W: In terms now ~of where this goes~, we've already heard some very strong, very emotional language from the camp of the man who appears to be on the losing side of all this, Dr. Abdullah Abdullah. What have you been ~saying~ to him in order to try ~and~ ~calm~ those feelings?
- M: Well, we have ~heard~ talk about establishing a [[file:2020112217-parallel.org][parallel]] presidency. We made clear that the United States and~its partners are not in a position to support a divided Afghanistan. That any effort to establish a parallel presidency would make it~impossible for the United States and its partners to continue their financial, economic and military support, and that the consequences for the country would be potentially quite terrible. Clearly, this is not something the Afghan population wants. It's not something they were voting for. And it's not something that they expect to happen, but it could be the consequences of an ill-considered action.

* 18-8-interview(2) 
- W: Let me turn it on to the man who may ~end up~ the winner, Mr. Ashraf Ghani. What pressure, if any, are you trying to bring on him to ensure that whatever happens he tried to include Abdullah Abdullah, or Abdullah Abdullah's people in any future government?
- M: We're not making any [[file:2020112313-assumptions.org][assumptions]] about who might be the winner or who might be the loser, and we think it's [[file:2020112311-premature.org][premature]] for anybody to be doing so. We've made clear to both candidates ~that*~ two things need* to happen. First of all, there needs to be a [[file:2020112313-robust.org][robust]] and transparent process for determining the winner, and there's still a good deal of work to be done there. And second*ly, we believe that both candidates need*to begin discussing the formation of a government that would have the support of all important components and elements within the country, a government of national unity that would~ensure that all of the significant [[file:2020112314-sectors.org][sectors]] of Afghan society feel included.
- W: You're saying it's all a bit [[file:2020112314-hasty.org][hasty]] to say whether one side or the other has won or lost. It is difficult, is it not, to see this result being overturned? This is a flat margin of victory at the moment -- 56 percent to 44 percent. It would be extraordinary to see the result overturned in the space of a couple of weeks.
- M: I think both candidates have agreed that there was extensive [[file:2020112314-fraud.org][fraud]] in the electoral process. Both candidates have agreed that the [[file:2020112314-suspect.org][suspect]] [[file:2020112314-ballots.org][ballots]] need to be audited. They haven't agreed on exactly how to go about that. We believe it's the responsibility of the electoral institutions to go ahead and conduct that kind of broad audit, whether or not the candidates have agreed on every [[roam:precise]] element of the process, they will have to do it. And we believe until they've done so it's premature to be coming to any judgments.
- W: It is worrying though, isn't it? I suppose it was all too predictable that democracy is an imperfect thing in Afghanistan and that undoubtedly there has been fraud, we've heard all sorts of reports that project there have been a measure of fraud, and whoever was going to lose in this election was going to say it's been by unfair means.
- M: I agree with you that Afghanistan is a relatively new democracy. The countries at this stage of democratic development often have difficulties of this sort. That there's not a tradition of good losers in societies at this level of political development. And in that sense, the problem we face is not unparalleled. There are other countries who have gone through similar difficulties. Nevertheless, the fact is that millions of Afghans went out and voted in the expectation that their vote would count. The numerous polls indicate that most Afghans are prepared to support either candidate as the victor. That most Afghans have said that they could accept the person they didn't vote for winning the election if that was the result. So while the problems we face are not unparalleled, the Afghan voters expect something better.
- W: James, I'm so grateful to you. I hugely appreciate you answering it and answering all the other questions as well.
- M: Pleasure.
