#+title: English Listening Skill

* 19-8-interview(2)
- [[file:2020111910-disciplinary.org][disciplinary]]
- [[file:2020111910-literacy.org][literacy]]
sciplinary literacy (学科素养)
- [[file:2020110313-convince.org][convince]]
- [[file:2020111911-affiliation.org][affiliation]]
- [[file:2020111911-assessment.org][assessment]]
- [[file:2020111911-interpreting.org][interpreting]]
- [[file:2020111911-sophisticated.org][sophisticated]]
- [[file:2020111911-weigh.org][weigh]]
- [[file:2020111911-engage.org][engage]]
  
* 19-8-interview(1)
- hey cathy did you read this article in this magazine?I cant believe how much man is changing the planet.
- yeah I had a look at it, quite intresting I suppose if you believe that sort of thing
- what? what do you mean if you believe that sort of thing
- are you saying you dont believe that we are damaging the planet?
- to be honest mark, not really
- what do you saying, are you saying global warming isn't a fact, deforestation isn't a fact, the greenhouse effect isn't actually happening?
- hey calmdown mark, I just think too many people take these things as been(❎) being(✔) definitely true without knowking all the facts
- you really dont think global warming is happening
- you know they have said sea levels are going to rise by quite a few meters over the next fifty to a hundread years
- wheather conditons are getting worse all over the world
- can you remember how many big hurricanes there have been in the country over the last few years
- I think evidence is around us
- I dont think we have enough infomation to be honest, we have only being measuring these things for around two or three hundread years
- we have no idea what was happening fifty thousands years ago.
- for all we know this is just a natural [[file:2020111916-blip.org][blip]], a kind of sudden but temperary change, in the whole climate cycle
- I dont think we should change how we living just because of twenty years of abnormal measurements.
- and dont you think all the other effcets we are having on the planets are destructive?
- and what do you mean?
- I mean like deforestation,overpopulation,threatening the existence of extincting(many endangerd) animals, the pollution of the air and the seas
- I mean I could go on if you want
- no, no, I understand what you are saying and yes .it is true that  there are several problems worldwide caused by human influence
- I think the destruction of amazon rainforest is really dangerous, and it is some thing we could leave(live(✔)) to regred([[file:2020111916-regret.org][regret]](✔)).
- I read somewhere that they were considered to be the lungs of the planet. and there we are happily chopping it all down.
- and it would be a shame to lose some of those animals that may become extinct, you know like the [[file:2020111915-rhino.org][rhino]] or the panda
- but I dont think we shoudn't interfer with nature.
- if they are going to be coming(becomme) extinct then we have to allow nature to take its caulse(course).
- you have just contradicted yourself in two sentences, cathy, first you said it is bad that we are interfering with nature by destroing the rainforest and then. 
- that is not the same thing
- well,ofcoures it is. the only reason 99 percent of these animal are endangerd is precisely becaulse we are threatening their habittats([[file:2020111916-habitats.org][habitats]])
- eighter by [[file:2020111916-chopping.org][chopping]] it down as you said(say) or by expanding towns and farming into areas where these animal normally live and hunt.
- you cant destory (an) animal's habitat and (then) turn aroud and said we can't [[file:2020111916-interfere.org][interfere]] with nature to save them(it).
- I don't think having twenty +pound caps+ panda cubs in zoos aroud the world is a very smart way to save +the+ a animal
- It is totally artificial and is crude to animals invovled
- I would go along with that, the real 
  
* 19-8-minilecture(3)
- here is what we find on dominance hormone.
- from their baseline when +them+ they come in , high power people experience about a twenty percent increase, ~and~ low power people experience abot a ten percent decrease.
- so again, two minuites and you +got+ get these changes.
- concerning stress hormone, high-power people experience about ~a~ twenty five percent decrease and ~the~ low-power people experience about 15% increase.
- Once again, two minutes +led+ lead to those hormone +not+ changes, that +can figures+ configure your brain to basiclly be +ever+ eigther +asative+ [[file:2020112115-assertive.org][assertive]] confident or really +active+ stress-reactive, +you know or and+ and you know feeling a sort of +shutdown+ shut down.
- and we all have that feeling right
- so it seems that +we worribles+ our [[file:2020112116-nonverbals.org][nonverbals]] do govern how we think and feel about ourselves
- also our bodies change our minds.so
- so power +paulsing+ posing for ~a few~ minuites really +change+ changes your life +for+ in meaningful ways.
- when I tell people about +these+ this, that our +body changes+ bodies change our +mind+ minds and our minds can change our +behaviors+ behavior
- and ~our~ behavior can change our outcomes they +said+ say to me i dont believe that. it feels fake right so i said fake it till u make it.
- I am going to live you with +these+ this
- before for you go in to the next stressful evalutataive situation for example a job interview +do this with two minutes+ for two minutes try +to do+ doing this.
- in the elevator or +the+ at your desk behind the +close+ closed door, and say to yourself +that+ that's what I want to do
- configure your brain to do the best in that situation
- get your dominance hormone up and get your stress hormone down
- dont leave that situation ~feeling~ like oh I +don't+ didn't show them who I am
- leave that situation +to say+ feeling like oh I really managed to say who I am and show +them+ who I am
- to sum up today we  talked abot the [[file:2020112116-nonverbals.org][nonverbal]] expression of power and  dominance and stress  and the +power+ stronng +infacts benefit to change t+ effects of ~the~  +changing+ change of +our+ +behaviors+ behavior
- I suggest you try power posing which is simple. but  will significant change the outcome of your life
- ok next time we are going to discuss the social functions of body language

  
* 19-8-minilecure(1)
- Body Language and Mind
- Good morning, everyone.
- In today's lecture, I'd like to focus on how our body language ~reveals~ who we are.
- We're really fascinated with body language, and particularly interested in other people's body language.
- You know, we're sometimes interested in an awkward interaction, or a smile, or a [[file:2020112117-contemptuous.org][contemptuous]] glance, or maybe a very awkward [[file:2020112117-wink.org][wink]], or handshake.
- So what kind of body language am I talking about?
- I am interested in power dynamics -- that is the nonverbal expressions of power and dominance.
- And what are nonverbal expressions of power and dominance?
- Well, this is what they are.
- In the animal kingdom, nonverbal expressions of power and dominance are about expanding.
- So you make yourself big, you stretch out, you take up space and you're basically opening up.
- And... and humans do the same thing.
- So they do this when they're feeling powerful in the moment.
- And this one is especially interesting because it really shows us how universal and old these expressions of power are.
- For example, when ~athletes~ cross the finish line and ~they've won~, it doesn't ~matter if~ they've never seen anyone do it. They do this.
- So the arms are up in ~the V sign~, the chin is [[file:2020112117-slightly.org][slightly]] lifted.
- But what do we do when we feel powerless?
- We do exactly the opposite. We close up. We make ourselves small.
- We don't want to [[file:2020112117-bump.org][bump]] into the person next to us.
- And this is what happens when you put together high and low power.
- So what we tend to do when it comes to power is that we complement the other's nonverbals.
- What I mean is if someone is being really powerful with us, we tend to make ourselves smaller.
- We don't mirror them. We do the opposite.
- I'm watching this behavior in the classroom, and guess what I have noticed.
- I notice that [[file:2020112117-mba.org][MBA]] students really ~exhibit~ the full range of power nonverbals.
- They get right into the middle of the room before class even starts, like they really want to occupy space.
- When they sit down, they're [[file:2020112117-sort_of.org][sort of]] spread out. They raise their hands high.
- You have other people who are [[file:2020112117-virtually.org][virtually]] collapsing when they come in.
- As soon as they, I mean other people, come in, you see it.
- You see it on their faces and their bodies, and they sit with their chairs and they make themselves tiny,
- and they will not fully stretch their arms when they raise their hands.


