#+title: Word Power Made Easy
* How to use this book for maximum benefit
- [[file:2020111921-syllable.org][syllable]]
- [[file:2020111921-egomaniacal.org][egomaniacal]]
- [[file:2020111921-altercation.org][altercation]]
- [[file:2020111921-anthropological.org][anthropological]]
- [[file:2020111921-hissed.org][hissed]]
- [[file:2020112019-ambivalence.org][ambivalence]]
- [[file:2020112019-opulence.org][opulence]]
- [[file:2020112019-malign.org][malign]]
- [[file:2020112019-pagan.org][pagan]]
- [[file:2020112019-martinet.org][martinet]]
- [[file:2020112019-magnate.org][magnate]]
- [[file:2020112019-clandestinely.org][clandestinely]]
- [[file:2020112019-concerto.org][concerto]]
- [[file:2020112019-sorority.org][sorority]]
- [[file:2020112019-incorrigible.org][incorrigible]]
- [[file:2020112019-disparage.org][disparage]]
- [[file:2020112019-marry.org][marry]]
- [[file:2020112019-astronaut.org][astronaut]]
- [[file:2020112019-subtle.org][subtle]]
- [[file:2020112019-convention.org][convention]]
- [[file:2020112019-equivocate.org][equivocate]]
- [[file:2020112019-alternate.org][alternate]]
- [[file:2020112019-philander.org][philander]]
- [[file:2020112019-egoistic.org][egoistic]]
- [[file:2020112019-introverted.org][introverted]]
- [[file:2020112019-misogynous.org][misogynous]]
- [[file:2020112019-latent.org][latent]]
* How to test your present vocabulary
- [[file:2020112019-virtuoso.org][virtuoso]]
- [[file:2020112020-bumbling.org][bumbling]]
- [[file:2020112020-insulting.org][insulting]]
- [[file:2020112020-astonishing.org][astonishing]]
- [[file:2020110314-assess.org][assess]]
- [[file:2020112020-grasp.org][grasp]]
- [[file:2020112020-executives.org][executives]]
- [[file:2020112020-intimately.org][intimately]]
- [[file:2020112020-attaining.org][attaining]]
- [[file:2020112020-radical.org][radical]]
- [[file:2020112020-lull.org][lull]]
- [[file:2020112020-nuisance.org][nuisance]]
- [[file:2020112020-airy.org][airy]]
- [[file:2020112020-prodigious.org][prodigious]]
- [[file:2020112020-delusion.org][delusion]]
- [[file:2020112020-methuselah.org][methuselah]]
- [[file:2020112020-superstition.org][superstition]]
- [[file:2020112020-insatiable.org][insatiable]]
- [[file:2020112020-aspect.org][aspect]]
- [[file:2020112020-teaser.org][teaser]]
- [[file:2020112021-ramification.org][ramification]]
- [[file:2020112021-accustomed.org][accustomed]]
- [[file:2020112021-approximately.org][approximately]]
- [[file:2020112021-assimilate.org][assimilate]]
- [[file:2020112021-gobbing.org][gobbing]]

* How to talk about personality types
** SESSION 1
*** IDEAS
**** [[file:2020112021-egoist.org][egoist]]
- [[file:2020112021-aboveboard.org][aboveboard]]
**** [[file:2020112109-egotist.org][egotist]]
- [[file:2020112021-conceit.org][conceit]]
- [[file:2020112021-amorous.org][amorous]]
- [[file:2020112021-boastful.org][boastful]]
- [[file:2020112021-obnoxious.org][obnoxious]]
- [[file:2020112021-interest.org][interest]]
**** [[file:2020112021-altruist.org][altruist]]
**** [[file:2020112021-introvert.org][introvert]]
- [[file:2020112219-probing.org][probing]]
- [[file:2020112021-nagging.org][nagging]]
- [[file:2020112108-solitude.org][solitude]]
**** [[file:2020112108-extrovert.org][extrovert]]
- [[file:2020112108-dignity.org][dignity]]
- [[file:2020112108-propriety.org][propriety]]
**** [[file:2020112108-ambivert.org][ambivert]]
- [[file:2020112108-proportion.org][proportion]]
**** [[file:2020112108-misanthrope.org][misanthrope]]
- [[file:2020112108-embittered.org][embittered]]
- [[file:2020112108-crookedness.org][crookedness]]
**** [[file:2020112108-misogynist.org][misogynist]]
- [[file:2020112108-scorned.org][scorned]]
**** [[file:2020112108-misogamist.org][misogamist]]
**** [[file:2020112108-ascetic.org][ascetic]]
- [[file:2020112108-heir.org][heir]]
- [[file:2020112111-austerity.org][austerity]]
- [[file:2020112108-abstinence.org][abstinence]]
*** SESSION 2
**** Origin and relative words
- [[file:2020112109-excursions.org][excursions]]
***** the ego
- √ego meaning "I"
- [[file:2020112109-egomaniac.org][egomaniac]]
  - [[file:2020112109-morbid.org][morbid]]
  - [[file:2020112109-obsession.org][obsession]]
  - [[file:2020112109-mania.org][mania]]
***** others √alter
- [[file:2020112021-altruist.org][altruist]]
- [[file:2020112019-alternate.org][alternate]]
- [[file:2020112109-alternative.org][alternative]]
- [[file:2020111921-altercation.org][altercation]] is a verbal [[file:2020112109-dispute.org][dispute]]. is stronger than [[file:2020112109-quarrel.org][quarrel]] or [[file:2020112109-dispute.org][dispute]] the [[file:2020112109-sentiment.org][sentiment]], the disagreement is likely to be angry or even hot tem-tempered, there maybe [[file:2020112109-recourse.org][recourse]], if the [[file:2020112109-disputants.org][disputants]] are human, to [[file:2020112109-profanity.org][profanity]] or [[file:2020112109-obscenity.org][obscenity]], the word implies that you get quite excited.
- [[file:2020112109-alteration.org][alteration]] is of course a change, a making into something other.
- [[file:2020112109-alter_ego.org][alter ego]] 
**** Using the word
- [[file:2020112109-blow.org][blow]]
- [[file:2020112110-substitutes.org][substitutes]]
*** SESSION 3
**** Origin and relative words
***** depends how you turn
- √verto to turn
- the prefix ambi- also found in [[file:2020112110-ambidexterity.org][ambidexterity]]
  - [[file:2020112110-dexterous.org][dexterous]] means skillful, the noun [[file:2020112110-dexterity.org][dexterity]] is skill.
  - [[file:2020112110-dexter.org][dexter]] is a latin word for right hand, in the [[file:2020112110-ambidextrous.org][ambidextrous]] person both hands are right hands.
  - [[file:2020112110-left_handed.org][left-handed]] is still the synonym of awkward
  - the Latin word for the left hand is [[file:2020112110-sinister.org][sinister]]
  - The French word for the left hand is [[file:2020112110-gauche.org][gauche]]. A [[file:2020112110-gauche.org][gauche]] remark is [[file:2020112110-tactless.org][tactless]]. A [[file:2020112110-gauche.org][gauche]] offer of a sympathy is so [[file:2020112020-bumbling.org][bumbling]] to be embarassing. [[file:2020112110-gaucherie.org][gaucherie]] is an awkward, [[file:2020112110-clumsy.org][clumsy]], [[file:2020112110-tactless.org][tactless]], embarrassing way of saying things or of handling situation. The [[file:2020112110-gauche.org][gauche]] person is totally without [[file:2020112110-finesse.org][finesse]].
  - And the French word for the right hand is [[file:2020112110-droit.org][droit]], which we have used in building our English word adroit ( a-DROYT'). Needless to say, adroit, like dexterous, means skillful, but especially in the exercise of the mental [[file:2020112110-facilities.org][facilities]]. Like gauche, adroit, or its [[file:2020112110-nounadroitness.org][nounadroitness]], usually is used [[file:2020112110-figuratively.org][figuratively]]. The adroit person is quick-witted, can get out of difficult spots cleverly, can handle situations [[file:2020112110-ingeniously.org][ingeniously]]. Adroitness is, then, quite the opposite of gaucherie.
***** love,hate,and marriage
****** √misein to hate
Misanthrope, misogynist, and misogamist are built on the Greek root ~misein~, to hate. The misanthrope hates mankind (Greek ~anthropos~, mankind); the misogynist hates women (Greek ~gyne~, woman); the misogamist hates marriage (Greek ~gamos~, marriage). Anthropos, mankind, is also found in [[file:2020112110-anthropology.org][anthropology]] (an-thra-POL'-a-jee), the study of the development of the human race; and in [[file:2020112110-philanthropist.org][philanthropist]] (fa-LAN'-thra-pist), one who loves man-kind and shows such love by making [[file:2020112110-substantial.org][substantial]] financial contributions to charitable organizations or by donating time and energy to helping those in need. The root gyne, woman, is also found in [[file:2020112110-gynecologist.org][gynecologist]]  jin· -KOL'-a-jist, the medical specialis treats female disorders. And the root gamos, marriage, occurs also in [[file:2020112110-monogamy.org][monogamy]] (rna-NOG'-a-mee), [[file:2020112110-bigamy.org][bigamy]] (BIG'-a-rnee), and [[file:2020112110-polygamy.org][polygamy]] (pa-LIG'-a-mee). (As we will discover later, monos means one, bi- means two, polys means many.)
So monogamy is the custom of only one marriage (at a time).
Bigamy, by etymology, is two marriages-in actuality, the unlawful act of contracting another marriage without divorcing one's current legal spouse.
And polygamy, by derivation many marriages, and therefore etymologically [[file:2020112111-denoting.org][denoting]] [[file:2020112111-plural.org][plural]] marriage for either males or females, in current usage generally refers to the custom practiced in earlier times by the [[file:2020112111-mormons.org][Mormons]], and before them by King Solomon, in which the man has as many wives as he can afford financially and/or emotionally. The correct, but rarely used, term for this custom is polygyny (p;;i-LIJ'-a-nee)-polys, many, plus gyne,woman.
What if a woman has two or more husbands, a form of marriage practiced in the Himalaya Mountains of Tibet? That custom is called [[file:2020112111-polyandry.org][polyandry]] (pol-ee-AN'-dree), from polys plus Greek
~andros~, male.
***** making friends with suffixes
***** living alone and liking it √asketes
[[file:2020112111-ascetic.org][Ascetic]] is from the Greek word ~asketes~, monk or hermit.
A monk lives a lonely life-not for him the pleasures of the fleshpots, the [[file:2020112111-laughter.org][laughter]] and [[file:2020112111-merriment.org][merriment]] of [[file:2020112111-convivial.org][convivial]] gatherings, the [[file:2020112111-dissipation.org][dissipation]] of high living. Rather, days of contemplation, study, and rough [[file:2020112111-toil.org][toil]], nights on a hard bed in a simple cell, and the kind of self-denial that leads to a [[file:2020112111-purification.org][purification]] of the soul.
That person is an ascetic who leads an existence, voluntarily of course, that compares in [[file:2020112111-austerity.org][austerity]], simplicity, and [[file:2020112111-rigorous.org][rigorous]] hardship with the life of a monk.
The practice is [[file:2020112111-asceticism.org][asceticism]] (a-SET'-;l-siz-am), the adjective ascetic.
**** REVIEW OF [[file:2020112111-etymology.org][ETYMOLOGY]]
| ego       | self, I                  |
| alter     | other                    |
| intro-    | inside                   |
| extro-    | outside                  |
| verto     | turn                     |
| ambi-     | both                     |
| misein    | hate                     |
| anthropos | mankind                  |
| gyne      | woman                    |
| gamos     | marriage                 |
| asketes   | monk                     |
| centrum   | center                   |
| mania     | madness                  |
| dexter    | right hand               |
| sinister  | left hand                |
| gauche    | left hand                |
| droit     | right hand               |
| monos     | one                      |
| bi-       | two                      |
| polys     | many                     |
| andros    | male                     |
| -ist      | person who (noun suffix) |
| -y        | practive custiom ,etc.   |
| -ous      | adjective suffix         |
| -ity      | quality condition        |

**** Using the words
- [[file:2020112113-asset.org][asset]]
- [[file:2020112113-hatred.org][hatred]]

**** TEASER QUESTIONS FOR THE AMATEUR ETYMOLOGIST
- [[file:2020112113-anthropocentric.org][anthropocentric]]
- [[file:2020112113-andromania.org][andromania]]
- [[file:2020112113-gynandrous.org][gynandrous]]
- [[file:2020112113-monomania.org][monomania]]
- [[file:2020112113-misandrist.org][misandrist]]

**** STICK TO YOUR TIME SCHEDULE!
- [[file:2020112113-unduly.org][unduly]]
- [[file:2020112113-gratified.org][gratified]]
- [[file:2020112113-thrill.org][thrill]]
- [[file:2020112114-persevere.org][persevere]]

* Brief [[file:2020112114-intermission.org][Intermission]] One
** TEST YOUR GRAMMAR
*** TEST1
- [[file:2020112114-proper.org][proper]]
*** TEST2
- [[file:2020112114-cinch.org][cinch]]
*** TEST3
- [[file:2020112114-creditably.org][creditably]]
- [[file:2020112114-criteria.org][criteria]]
* HOW TO TALK ABOUT DOCTORS
- [[file:2020112115-ailments.org][ailments]]
** SESSION5
*** IDEAS
**** what's wrong with you?
To find out what ails you and why, this specialist gives you a thorough physical examination, using an impressive array of tests: X ray,. blood chemistry, urinalysis, cardiogram, and so on.
An [[file:2020112209-internist.org][internist]]

**** female troubles?
This specialist treats the female reproductive and sexual organs.
A [[file:2020112110-gynecologist.org][gynecologist]]

**** having a baby?
This specialist delivers babies and takes care of the mother during and immediately.after the period of her pregnancy.
An [[file:2020112209-obstetrician.org][obstetrician]]

**** is your baby ill?
You know the common childhood maladies-mumps, whooping cough, chicken pox, [[file:2020112209-measles.org][measles]]. This specialist limits his practice to youngsters, taking care of babies directly after birth, [[file:2020112209-supervising.org][supervising]] their diet and watching over their growth and development, giving them the series of [[file:2020112209-inoculations.org][inoculations]] that has done so much to decrease infant [[file:2020112209-mortality.org][mortality]], and [[file:2020112209-soothing.org][soothing]] their anxious parents.
A [[file:2020112209-pediatrician.org][pediatrician]]

**** skin clear?
You have heard the classic [[file:2020112209-riddle.org][riddle]]: "What is the best use for pigskin?" Answer: "To keep the pig together." Human skin has a similar purpose: it is, if we get down to fundamentals, what keeps us all in one piece. And our outer covering, like so many of our internal organs, is subject to diseases and infections of various kinds, running the [[file:2020112209-gamut.org][gamut]] from simple [[file:2020112209-acne.org][acne]] and [[file:2020112209-eczemas.org][eczemas]] through [[file:2020112209-impetigo.org][impetigo]], [[file:2020112209-psoriasis.org][psoriasis]], and cancer. There is a specialist who treats all such skin diseases. 
A [[file:2020112209-dermatologist.org][dermatologist]]

**** eyes okay?
The physician whose specialty is disorders of vision ([[file:2020112209-myopia.org][myopia]], [[file:2020112209-astigmatism.org][astigmatism]], [[file:2020112209-cataracts.org][cataracts]], [[file:2020112209-glaucoma.org][glaucoma]], etc.) may [[file:2020112209-prescribe.org][prescribe]] glasses, administer drugs, or perform surgery.
An [[file:2020112209-ophthalmologist.org][ophthalmologist]]

**** how are your bones?
This specialist deals with the skeletal structure of the body, treating bone fractures, slipped discs, [[file:2020112209-clubfoot.org][clubfoot]], [[file:2020112209-curvature.org][curvature]] of the spine, dislocations of the hip, etc., and may correct a condition either by surgery or by the use of braces or other appliances.
An [[file:2020112209-orthopedist.org][orthopedist]]

**** does yaur heart go pitter-patter?
This specialist treats diseases of the heart and circulatory system.
A [[file:2020112209-cardiologist.org][cardiologist]]

**** 9. is your brain working?
This physician specializes in the treatment of disorders of the brain, spinal cord, and the rest of the nervous system.
A [[file:2020112209-neurologist.org][neurologist]]

**** are you neurotic?
This specialist attempts to [[file:2020112209-alleviate.org][alleviate]] mental and emotional disturbances by means of various techniques, occasionally drugs or electroshock, more often private or group psychotherapy.
A [[file:2020112209-psychiatrist.org][psychiatrist]]

*** ORIGINS AND RELATED WORDS
**** inside you
Internist and internal derive from the same Latin root, ~internus~, inside. The internist is a specialist in internal medicine, in the exploration of your insides. This physician determines the state of your internal organs in order to discover what's happening within your body to cause the troubles you're complaining of. Do not confuse the internist with the [[file:2020112210-intern.org][intern]] (also spelled interne), who is a medical graduate serving an [[file:2020112210-apprenticeship.org][apprenticeship]] inside a hospital

**** doctors for women
The word [[file:2020112110-gynecologist.org][gynecologist]] is built on Greek ~gyne~, woman, plus ~logos~, science; etymologically, gynecology is the science (in actual use, the medical science) of women. [[file:2020112210-adjective.org][Adjective]]: gynecological (gin [or jin or jinJ-a-kQ-LOJ'-a-kal). [[file:2020112210-obstetrician.org][Obstetrician]] derives from Latin ~obstetrix~, midwife, which in turn has its source in a Latin verb meaning to stand-midwives stand in front of the woman in labor to aid in the delivery of the infant. The suffix ~-ician~, as in obstetrician, physician, musician, magi- cian, electrician, etc., means expert. Obstetrics (ob-STET'-riks) has only within the last 150 years become a respectable specialty. No further back than 1834, Professor William P. Dewees [[file:2020112210-assumed.org][assumed]] the first chair of obstetrics at the University of Pennsylvania and had to brave considerable medical contempt and [[file:2020112210-ridicule.org][ridicule]] as a result-the delivery of children was then considered beneath the [[file:2020112108-dignity.org][dignity]] of the medical profession. Adjective: obstetric (ob-STET'-rik) or obstetrical (ob-STET'- ra-kal).

**** children
Pediatrician is a combination of Greek ~paidos~, child; ~iatreia~, medical healing; and -ician, expert. · Pediatrics (pee-dee-AT'-riks), then, is by etymology the medical healing of a child. Adjective: pediatric (pee-dee-AT'-rik). (The ped- you see in words like [[file:2020112210-pedestal.org][pedestal]], [[file:2020112210-pedal.org][pedal]], and [[file:2020112210-pedestrian.org][pedestrian]] is from the Latin ~pedis~, foot, and [[file:2020112210-despite.org][despite]] the identical spelling in English has no relationship to Greek ~paidos~.) [[file:2020112210-pedagogy.org][Pedagogy]] (PED-a-go'-jee), which combines ~paidos~ with ~agogos~, leading; is, etymologically, the leading of children. And to what do you lead them? To learning, to development, to growth, to maturity. From the moment of birth, infants are led by adults- they are taught, first by parents and then by teachers, to be self-sufficient, to *fit into* the culture in which they are born. Hence, pedagogy, which by derivation means the leading of a child, refers actually to the principles and methods of teaching. College students majoring in education take certain standard pedagogy courses-the history of education; educational psychology; the psychology of [[file:2020112210-adolescents.org][adolescents]]; principles of teaching; etc. Adjective: pedagogical (ped-a-GOJ'-a-kal). A pedagogue (PED'-:i-gog) is versed in pedagogy. But [[file:2020112210-pedagogue.org][pedagogue]] has an unhappy history. From its original, neutral meaning of teacher, it has deteriorated to the point where it refers, today, to *a* *narrow-minded*,[[file:2020112210-strait_laced.org][strait-laced]] ,old-fashioned, [[file:2020112210-dogmatic.org][dogmatic]] teacher. It is a word of contempt and should be used with caution. Like. pedagogue, [[file:2020112210-demagogue.org][demagogue]] (DEM'-a-gog) has also deteriorated in meaning. By derivation a leader (agogos) of the people (~demos~), a demagogue today is actually one who attempts, in [[file:2020112210-essence.org][essence]], to mislead the people, a politician who foments discontent among the masses, [[file:2020112210-rousing.org][rousing]] them to fever [[file:2020112210-pitch.org][pitch]] by wild [[file:2020112210-oratory.org][oratory]], in an attempt to be voted into office. Once elected, demagogues use political power to further their
own personal ambitions or fortunes. Many "leaders" of the past and present, in countries around the world, have been [[file:2020112210-accused.org][accused]] of demagoguery ( dem-a-(]OG' -a-ree) . Adjective: demagogic (dem-a-GOJ'-ik).
**** skin-deep
The [[file:2020112209-dermatologist.org][dermatologist]], whose specialty is dermatology ( dur-ma- TOL'-a-jee), is so named from Greek ~derma~, skin. Adjective: dermatological ( dur'-ma-ta-LOJ'-a-kal). See the syllables derma in any English word and you will know there is some reference to skin-for example, a [[file:2020112210-hypodermic.org][hypodermic]] . (hi~ pa-DUR'..,mik) needle [[file:2020112210-penetrates.org][penetrates]] under (Greek, ~hypos~) the skin,· the [[file:2020112210-epidermis.org][epidermis]] (ep-:i-DUR'-mis) ·is the outermost layer of skin; a [[file:2020112210-taxidermist.org][taxidermist]] (TAKS'-a-dur-mist), whose business is [[file:2020112210-taxidermy.org][taxidermy]] (TAKS'-a-dur-mee), prepares, stuffs, and mounts the skins of animals; a [[file:2020112210-pachyderm.org][pachyderm]] (PAK'-a-durm) is an animal with an unusually [[file:2020112210-thick.org][thick]] skin, like an elephant, [[file:2020112210-hippopotamus.org][hippopotamus]], or [[file:2020112210-rhinoceros.org][rhinoceros]]; and [[file:2020112210-dermatitis.org][dermatitis]] (dur-ma-Ti'-tis) is the general name for any skin inflammation, [[file:2020112210-irritation.org][irritation]], or infection.
**** the eyes have it
Ophthalmologist-note the ph preceding th-is from Greek ~ophthalmos~, eye, plus ~·logos~, science or study. The specialty is ophthalmology (off'-thal-MOU-a-jee), the adjective ophthal-mological ( off'-thal-ma-LOJ'-a-kal). An earlier title for this physician, still occasionally used, is ocu- list (OK'-ya-list), from Latin [[file:2020112210-oculus.org][oculus]], eye, a root on which the following English words are also built:
1. [[file:2020112210-ocular.org][ocular]] (OK'-ya-Iar)-an adjective that refers to the eye
2. [[file:2020112210-monocle.org][monocle]] (MON'-a-kal)-a lens for one (monos) eye, sported by characters in old movies as a symbol of the British so-called upper class
3. [[file:2020112210-binoculars.org][binoculars]] (ba-NOK'-ya-larz)-field glasses that increase the range of two (bi-) eyes
4. And, strangely enough, [[file:2020112210-inoculate.org][inoculate]] (in-OK'-ya-layt'), a word commonly [[file:2020112210-misspelled.org][misspelled]] with two n's. When you are inoculated against a disease, an "eye," [[file:2020112210-puncture.org][puncture]], or hole is made in your skin, through which [[file:2020112210-serum.org][serum]] is injected. Do not confuse the ophthalmologist or oculist, a medical specialist, with two other [[file:2020112210-practitioners.org][practitioners]] who deal with the eye-the [[file:2020112210-optometrist.org][optometrist]] (op-TOM'-a-trist) and [[file:2020112210-optician.org][optician]] (op-TISH'-an). Optometrists are not [[file:2020112210-physicians.org][physicians]], and do not perform surgery or administer drugs; they measure vision, test for [[file:2020112209-glaucoma.org][glaucoma]], and prescribe and fit glasses. Opticians fill an optometrist's or ophthalmologist's prescription, [[file:2020112211-grinding.org][grinding]] lenses according to specifications; they do not [[file:2020112211-examine.org][examine]] patients. Optometrist combines Greek ~opsis~, ~optikos~, sight or vision, with ~metron~, measurement .the optometrist, by etyi:pology, is one who measures vision. The specialty is [[file:2020112211-optometry.org][optometry]] (op-TOM'-a-tree).
Optician is built on opsis, optikos, plus -ician, expert. The specialty is optics (OP'-tiks). Adjectives: optometric ( op-ta-MET'-rik) or optometrical (op- ta-MET'-ra-kal), optical (OP'-ta-kal).
*** REVIEW OF ETYMOLOGY
| PREFIX, ROOT, SUFFIX | MEANING        |
|----------------------+----------------|
| internus             | inside         |
| gyne                 | woman          |
| obstetrix            | [[file:2020112211-midwife.org][midwife]]        |
| paidos               | child          |
| pedis                | foot           |
| agogos               | leader,leading |
| demos                | people         |
| derma                | skin           |
| hypos                | under          |
| ophthalmos           | eye            |
| oculus               | eye            |
| monos                | one            |
| bi-                  | two            |
| -ician               | expert         |
| opsis, optikos       | vision         |
| metron               | measurement    |
*** SESSION6
**** ORIGINS AND RELATED WORDS
***** the straighteners
The [[file:2020112209-orthopedist.org][orthopedist]] is so called from the Greek roots ~orthos~, straight or correct, and ~paidos~, child. The orthopedist, by etymology, [[file:2020112215-straightens.org][straightens]] children. The term was [[file:2020112215-coined.org][coined]] in 1741 by the author of a textbook on the [[file:2020112215-prevention.org][prevention]] of childhood diseases-at that time the correction of spinal [[file:2020112209-curvature.org][curvature]] in children was a main concern of practitioners of orthopedics ( awr-tha-PEE' -diks). Today the specialty treats [[file:2020112215-deformities.org][deformities]], [[file:2020112215-injuries.org][injuries]], and diseases of the bones and joints (of adults as well as children, of course), often by surgical procedures. Adjective: orthopedic (awr-tha-PEE'-dik). [[file:2020112215-orthodontia.org][Orthodontia]] (awr-tha-DON'-sha), the straightening of teeth, is built on ~orthos~ plus ~odontos~, tooth. The [[file:2020112215-orthodontist.org][orthodontist]] (aWl'-tha- DON'-tist) specializes in improving your "bite," retracting "[[file:2020112215-buck_teeth.org][buck teeth]]," and by means of braces and other techniques seeing to it
that every [[file:2020112215-molar.org][molar]], [[file:2020112215-incisor.org][incisor]], [[file:2020112215-bicuspid.org][bicuspid]], etc. is exactly where it belongs in your mouth.
Adjective: orthodontic (awr-tha-DON'-tik).
***** the heart
[[file:2020112215-cardiologist.org][Cardiologist]] combines Greek ~kardia~, heart, and ~logos~, science.
The specialty is cardiology (kahr-dee-OL'-a-jee), the adjective cardiological (kahr'-dee-a-LOJ'-a-kal).
So a cardiac (KAHR'-dee-ak) condition refers to some malfunctioning of the heart; a cardiogram (KAHR'-dee-a-gram') is an electrically produced record of the heartbeat. The instrument that produces this record is called a cardiograph (KAHR'-dee-a- graf').
***** the nervous system
Neurologist derives from Greek ~neuron~, nerve, plus logos, sci-
ence.
Specialty: neurology (noor-OL'-a-jee); adjective: neurological
(noor-a-LOJ'-a-kal).
[[file:2020112215-neuralgia.org][Neuralgia]] (noor-AL'-ja) is acute pain along the nerves and
their branches; the word comes from neuron plus ~algos~, pain.
[[file:2020112215-neuritis.org][Neuritis]] (noor-1'-tis), is [[file:2020112215-inflammation.org][inflammation]] of the nerves.
[[file:2020112215-neurosis.org][Neurosis]] (noor-0'-sis), combining neuron with ~-osis~, a ~suffix~ meaning abnormal or diseased condition, is not, [[file:2020112210-despite.org][despite]] its etymology, a disorder of the nerves, but rather, as· described by the late Eric Berne, a psychiatrist, "... an illness characterized by excessive use of energy for unproductive purposes so that personality development is [[file:2020112215-hindered.org][hindered]] or stopped. A man who spends most of his time worrying about his health, counting his money, [[file:2020112215-plotting.org][plotting]] revenge, or washing his  hands, can hope for little emotional growth." .
Neurotic (m;lOr-OT'-ik) is both the adjective form and the term
for a person suffering from neurosis.
***** the mind
A neurosis is not a form of mental unbalance. A full-blown mental disorder is called a [[file:2020112215-psychosis.org][psychosis]] (si-KO'-sis), a word built on Greek ~psyche~, spirit, soul, or mind, plus -osis. A true psychotic (si-KOT'-ik) has lost contact with reality-at least with reality as most of us [[file:2020112215-perceive.org][perceive]] it, though no doubt psychotic (note that this word, h"ke neurotic, is both a noun and an adjective) people have their own form of reality. Built on psyche plus ~iatreia~, medical healing, a psychiatrist by etymology is a mind-healer. The specialty is psychiatry (si- or sa- Kf-tree); the adjective is psychiatric (si~kee-AT'-rik).
[[file:2020112215-pediatrics.org][Pediatrics]], as you know, is also built on ~iatreia~, as is [[file:2020112215-podiatry.org][podiatry]] (p~-Df'-::>-tree), discussed, in the next chapter, and [[file:2020112215-geriatrics.org][geriatrics]]
(jair'-ee-AT'-riks), the specialty dealing with the particular medi-
cal needs of the elderly. (This word combines iatreia with. Greek
ge.ras, old age.)
The specialist is a geriatrician (jair'-ee-::>-TRISH'-~n), the ad-
jective is geriatric (jair'-ee-AT'-rik).
**** REVIEW OF ETYMOLOGY
| orthos        | straight,correct |
| paidos (ped-) | child            |
| odontos       | tooth            |
| kardia        | heart            |
| logos         | science          |
| neuron        | nerve            |
| algos         | pain             |
**** TWO KEYS TO. SUCCESS: SELF-DISCIPLINE AND PERSISTENCE
You can achieve a [[file:2020112216-superior.org][superior]] vocabulary in a [[file:2020112216-phenomenally.org][phenomenally]] short time-given self-discipline and persistence.
The greatest [[file:2020112216-aid.org][aid]] in building self-discipline is, as I have said, a matter of devising a practical and comfortable schedule for yourself and then keeping to that schedule.
 Make sure to complete at least one session each time you pick up the book, and always decide exactly when you will continue with your work before you put the book down.
There may be periods of difficulty-then is the time to exert the greatest self-discipline, the most determined persistence.
For every page that you study will help you [[file:2020112216-attain.org][attain]] a mastery over words; every day that you work will add to your skill in understanding and using words.

* Brief Intermission Two
** RANDOM NOTES ON MODERN USAGE
English grammar is confusing enough as it is-what makes it doubly confounding is that it is slowly but continually changing. •
This means that some of the strict rules you memorized so painfully in your high school or college English courses may no longer be completely valid.
Following such outmoded principles, you may think you are speaking "perfect" English, and instead you may sound [[file:2020112216-stuffy.org][stuffy]] and [[file:2020112216-pedantic.org][pedantic]].
The problem boils down to this: If grammatical usage is gradually becoming more liberal, where does educated, unaffected, informal speech end? And where does illiterate, ungrammatical speech begin?
The following notes on current trends in modem usage are intended to help you come to a decision about certain [[file:2020112216-controversial.org][controversial]] expressions. As you read each sentence, pay particular attention to the italicized word or words. Does the usage [[file:2020112216-square.org][square]] with your own language patterns? Would you be willing to phrase your thought in just terms? Decide whether the sentence is right or wrong, then compare your conclusion with the opinion given in the explanatory paragraphs that follow the test.
*** TEST 
- full-fleged
- [[file:2020112216-demise.org][demise]]
- [[file:2020112216-connecticut.org][connecticut]]
- [[file:2020112216-concedes.org][concedes]]
- [[file:2020112216-alumni.org][alumni]]
- [[file:2020112216-probability.org][probability]]
- [[roam:charitable-looking]]
- [[file:2020112216-seedy.org][seedy]]
- [[file:2020112216-handout.org][handout]]
- [[file:2020112216-whined.org][whined]]
- [[file:2020112216-matron.org][matron]]
* HOW TO TALK ABOUT VARIOUS PRACTITIONERS
** SESSION 7
An ancient Greek [[file:2020112217-mused.org][mused]] about the meaning of life, and philosophy was born. The first Roman decided fo build a road instead of cutting a path through the jungle, and engineering came into existence. One day in [[file:2020112217-primitive.org][primitive]] times, a human being [[roam:lent]] to another whatever then passed for money and got back his original investment plus a little more-and banking had started.
Most people Spend part of every workday at some gainful employment, honest or otherwise, and in so doing often contribute their little [[file:2020112217-mite.org][mite]] to the progress of the world.
We explore in this chapter the ideas behind people's occupations-and the words that translate these ideas into verbal symbols.
*** IDEAS
**** behavior
By education and training, this practitioner is an expert in the dark mysteries of human behavior-what makes people act as they do, why they have certain feelings, how their personalities were formed-in short, what makes them [[file:2020112217-tick.org][tick]]. Such a professional , is often employed by industries, schools, and institutions to devise  means for keeping workers productive and happy, students well-adjusted, and inmates contented. With a state license, this person may also do private or group therapy.
A [[file:2020112217-psychologist.org][psychologist]]

**** worries, fears, conflicts
This practitioner is a physician, psychiatrist, or psychologist who has been specially trained in the [[file:2020112217-techniques.org][techniques]] devised by Sigmund Freud, encouraging you to [[file:2020112217-delve.org][delve]] into that part of your mind called "the unconscious." By reviewing the experiences, [[roam:traumas]], feelings, and thoughts of your earlier years, you come to a better understanding of your present worries, fears, conflicts, repressions, insecurities, and nervous tensions-thus taking the first step in coping with them. Treatment, consisting largely in listening to, and helping you to [[file:2020112217-interpret.org][interpret]] the meaning of, your free-flowing ideas, is usually given in frequent sessions that may well go on for a year or more.
A [[file:2020112217-psychoanalyst.org][psychoanalyst]]

**** teeth
This practitioner is a dentist who has taken [[file:2020112217-postgraduate.org][postgraduate]] work in the straightening of teeth.
An [[file:2020112215-orthodontist.org][orthodontist]]

**** eyes
This practitioner measures your vision and prescribes the type of glasses that will give you a new and more accurate view of the world. ·
An [[file:2020112210-optometrist.org][optometrist]]

**** glasses
This practitioner [[file:2020112217-grinds.org][grinds]] lenses according to the specifications prescribed by your optometrist or ophthalmologist. and may also deal in other kinds of optical goods.
An [[file:2020112210-optician.org][optician]]

**** bones and blood vessels
This practitioner is a member of the profession that originated in 1874, when Andrew T. Still [[file:2020112217-devised.org][devised]] a drugless technique of curing diseases by massage and other manipulative procedures, a technique based on the theory that illness may be caused by the undue pressure of displaced bones on nerves and blood vessels. Training is equal to that of physicians, and in most states these practitioners may also use the same methods as, and have the full rights and privileges of medical doctors.
An [[file:2020112217-osteopath.org][osteopath]]

**** joints and articulations
The basic principle of this practitioner's work is the maintenance of the structural and functional integrity of the nervous system. Treatment consists of manipulating most of the [[file:2020112217-articulations.org][articulations]] of the body, especially those connected to the spinal column. Licensed and legally recognized in forty-five states, this professional has pursued academic studies and training that [[file:2020112217-parallel.org][parallel]] those of the major healing professions.
A [[file:2020112217-chiropractor.org][chiropractor]]

**** feet
This practitioner treats minor foot ailments-- [[file:2020112217-corns.org][corns]], [[file:2020112217-calluses.org][calluses]], [[file:2020112217-bunions.org][bunions]], fallen arches, etc., and may perform minor surgery.
A [[file:2020112217-podiatrist.org][podiatrist]]

**** writing
This practitioner analyzes handwriting to determine character, personality, or [[file:2020112217-aptitudes.org][aptitudes]], and is often called upon to verify the authenticity of signatures, written documents, etc.
A [[file:2020112217-graphologist.org][graphologist]]

**** getting old
This social scientist deals with the financial, economic, sexual, social, retirement, and other non-medical problems of the elderly.
A [[file:2020112217-gerontologist.org][gerontologist]]
*** SESSION 8
**** ORIGINS AND RELATED WORDS
***** the mental life
- Psychologist is built upon the same Greek root as psychiatrist-~psyche~, spirit, soul, or mind. In psychiatrist, the combining form is ~iatreia~, medical healing. In psychologist, the combining form is ~logos~, science or study; a psychologist, by etynmology, is one who studies the mind.
- The field is psychology (si-KOL'-~jee), the adjective psychological (si'-k~LOJ'-a-kal).
- [[file:2020112218-psyche.org][Psyche]] (SI'-kee) is also an English word in its own right..:._it designates the mental life, the spiritual or non-physical [[file:2020112020-aspect.org][aspect]] of one's existence. The adjective psychic (SI'-kik) refers to [[file:2020112218-phenomena.org][phenomena]] or qualities that cannot be explained in purely physical terms. People may be called psychic if they seem to possess a sixth sense, a special gift of mind reading, or any mysterious [[file:2020112217-aptitudes.org][aptitudes]] that cannot be accounted for logically. A person's [[file:2020112218-disturbance.org][disturbance]] is psychic if ii is emotional or mental, rather than physical.
- Psyche combines with the Greek ~pathos~, suffering or disease, to form [[file:2020112218-psychopathic.org][psychopathic]] (si-ka-PATH'-ik), an adjective that describes someone suffering from a severe mental or emotional disorder. The noun is psychopathy (sI'-KOP'~thee).*
- The root psyche combines with Greek ~soma~, body, to form psychosomatic (si'-ko-s::i-MAT'-ik), an adjective that [[file:2020112219-delineates.org][delineates]] the powerful influence that the mind, especially the unconscious, has on bodily diseases. Thus, a person who fears the consequence of being present at a certain meeting will suddenly develop a bad cold or backache, or even be injured in a traffic accident, so that his appearance at this meeting is made impossible. It's a real cold, it's far from [[file:2020112219-ari.org][ari]] imaginary backache, and of course one cannot in any sense doubt the reality of the automobile that injured him. Yet, according to the psychosomatic theory of medicine, his unconscious made him [[file:2020112219-susceptible.org][susceptible]] to the cold [[file:2020112219-germs.org][germs]], caused the backache, or forced him into the path of the car.
- A [[file:2020112219-psychosomatic.org][psychosomatic]] disorder actually exists [[file:2020112219-insofar.org][insofar]] as symptoms are concerned (headache, excessive urination, pains, paralysis, heart [[file:2020112219-palpitations.org][palpitations]]), yet there is no organic cause within the body. The cause is within the psyche, the mind. Dr. Flanders Dunbar, in Mind and Body, gives a clear and exciting account of the inter relationship between emotions and diseases.
- Psychoanalysis (si'-ko-a-NAL'-a-sis) relies on the [[file:2020112219-technique.org][technique]] of deeply, exhaustively [[file:2020112219-probing.org][probing]] into the unconscious, a technique developed by Sigmund Freud. In oversimplified terms, the general principle of psychoanalysis is to guide the patient to an awareness of the deep-seated, unconscious causes of anxieties, fears, conflicts, and tension. Once fourtd, exposed to the light of day, and [[file:2020112219-thoroughly.org][thoroughly]] understood, claim the psychoanalysts, these causes may [[file:2020112219-vanish.org][vanish]] like a light snow that is exposed to strong sunlight
- Consider an example: You have [[file:2020112219-asthma.org][asthma]], let us say, and your doctor can find no physical [[file:2020112219-basis.org][basis]] for your ailment. So you are referred to a psychoanalyst (or psychiatrist or clinical psychologist who practices psychoanalytically oriented therapy).
- With your therapist you explore your past life, dig into your un conscious, and discover, let us say for th~ sake of argument, that your mother or father always used to set for you impossibly high goals. No matter what you accomplished in school, it was not good enough in your mother's or father's opinion (and such opinions were always made painfully clear to you), you could do better if you were not so lazy. As a child you built up certain [[file:2020112219-resentments.org][resentments]] and anxieties because you seemed unable to please your parent-and (this will sound [[file:2020112219-farfetched.org][farfetched]], but it is perfectly possible) as a result you became asthmatic. How else were you going to get the parental love, the [[file:2020112219-approbation.org][approbation]], the attention you needed and that you felt you were not receiving?
- In your sessions with your therapist, you discover that your asthma is emotionally, rather than organically, based-your ailment is psychogenic (sI'-ko-JEN'-ik), of Psychic origin, or (the terms are used more or less interchangeably although they [[file:2020112219-differ.org][differ]] somewhat in definition) psychosomatic, resulting from the interaction of mind and body. ([[file:2020112219-psychogenic.org][Psychogenic]] is built on psyche plus Greek ~genesis~, birth or origin.)
- And your treatment? No drugs, no surgery-these may help the body, not the emotions. Instead, you "work out" (this is the term used in psychoanalytic [si-ko-an'-a-LIT'-ik] [[file:2020112219-parlance.org][parlance]]) early [[file:2020112219-trauma.org][trauma]] in talk, in remembering, in exploring, in interpreting, in reliving childhood experiences. And if your [[file:2020112219-asthma.org][asthma]] is indeed psychogenic (or psychosomatic), therapy will very likely help you; your attacks may [[file:2020112219-cease.org][cease]], either gradually or suddenly.
- [[file:2020112219-freudian.org][Freudian]] therapy is less popular today than formerly; many newer therapies-Gestalt, bioenergetics, [[file:2020112219-transactional.org][transactional]] analysis, to name only a few-claim to produce quicker results.
- In any case, psychotherapy (si-kO-THAIR'-a-pee)_ of one sort or another is the [[file:2020112219-indicated.org][indicated]] treatment for Psychogenic (or psycho- somatic) disorders, or for any personality disturbances. The practitioner is a [[file:2020112219-psychotherapist.org][psychotherapist]] (si-ko-THAIR'-a-pist) or therapist, for short; the adjective is [[file:2020112219-psychotherapeutic.org][psychotherapeutic]] (si-ko-thair'-a- PYOO'-tik).
#+BEGIN_QUOTE
[[file:2020112219-psychopathy.org][Psychopathy]] is usually [[file:2020112219-characterized.org][characterized]] by antisocial and extremely egocentric behavior. A psychopath (Sl'-ka-path'), sometimes called a psychopathic personality, appears to be lacking an inner moral censor, and often commits criminal acts, without anxiety or guilt, in order to obtain immediate [[file:2020112219-gratification.org][gratification]] of desires. Such a person may be [[file:2020112219-utterly.org][utterly]] lacking in sexual [[file:2020112219-restraint.org][restraint]], or addicted to hard drugs. Some psychologists prefer the label sociopath (SO'-shee-a-path' or SO>-see-:>-path') for this type of personality to [[file:2020112219-indicate.org][indicate]] the absence of a social [[file:2020112219-conscience.org][conscience]].
#+END_QUOTE

